import type { OccupationDefinition } from "../../coc7/types/occupation";

import { batch3aOccupationDefinitions } from "./occupations/batch3a";
import { batch2PressureOccupationDefinitions } from "./occupations/batch2-pressure";
import { batch2aOccupationDefinitions } from "./occupations/batch2a";
import { batch2bOccupationDefinitions } from "./occupations/batch2b";
import {
  anySkill,
  defineOccupation,
  edu2Plus,
  edu4,
  exact,
  investigatorHandbook,
  keeperRulebook,
  namedCustomSpecialization,
  oneOf,
  personalOrEraGuidance,
  predefined,
  requirement,
  socialSelector,
  specializationOf,
  standard,
} from "./occupations/shared";

export const standardOccupationDefinitions: readonly OccupationDefinition[] = [
  defineOccupation(
    "accountant",
    "会计师",
    "Accountant",
    [investigatorHandbook(70)],
    { min: 30, max: 70 },
    edu4,
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("law", exact(standard("law"))),
      requirement("library-use", exact(standard("library-use"))),
      requirement("listen", exact(standard("listen"))),
      requirement("persuade", exact(standard("persuade"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("personal-or-era-specialties", anySkill(), 2, 2, true, personalOrEraGuidance),
    ],
    "business-professional",
  ),
  defineOccupation(
    "antiquarian",
    "文物学家（原作向）",
    "Antiquarian",
    [
      keeperRulebook(40, "自由技能措辞"),
      investigatorHandbook(71, "个人或时代特长措辞；规范化为 broad selector 与 Keeper review"),
    ],
    { min: 30, max: 70 },
    edu4,
    [
      requirement("appraise", exact(standard("appraise"))),
      requirement("art-craft", specializationOf("art-craft")),
      requirement("history", exact(standard("history"))),
      requirement("library-use", exact(standard("library-use"))),
      requirement("other-language", specializationOf("language-other")),
      requirement("social", socialSelector),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "academic",
    { aliases: { zh: ["文物学家"] } },
  ),
  defineOccupation(
    "artist",
    "艺术家",
    "Artist",
    [keeperRulebook(40), investigatorHandbook(71)],
    { min: 9, max: 50 },
    edu2Plus("DEX", "POW"),
    [
      requirement("art-craft", specializationOf("art-craft")),
      requirement("history-or-natural-world", oneOf(
        exact(standard("history")),
        exact(standard("natural-world")),
      )),
      requirement("social", socialSelector),
      requirement("other-language", specializationOf("language-other")),
      requirement("psychology", exact(standard("psychology"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("personal-or-era-specialties", anySkill(), 2, 2, true, personalOrEraGuidance),
    ],
    "media-art",
  ),
  defineOccupation(
    "author",
    "作家（原作向）",
    "Author",
    [keeperRulebook(40), investigatorHandbook(72, "职业技能列表续至印刷页 73")],
    { min: 9, max: 30 },
    edu4,
    [
      requirement("literature", namedCustomSpecialization("art-craft", "文学", "Literature")),
      requirement("history", exact(standard("history"))),
      requirement("library-use", exact(standard("library-use"))),
      requirement("natural-world-or-occult", oneOf(
        exact(standard("natural-world")),
        exact(standard("occult")),
      )),
      requirement("other-language", specializationOf("language-other")),
      requirement("own-language", specializationOf("language-own")),
      requirement("psychology", exact(standard("psychology"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "media-art",
    { aliases: { zh: ["作家"] } },
  ),
  defineOccupation(
    "clergy",
    "神职人员",
    "Clergy, Member of the",
    [keeperRulebook(40), investigatorHandbook(74)],
    { min: 9, max: 60 },
    edu4,
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("history", exact(standard("history"))),
      requirement("library-use", exact(standard("library-use"))),
      requirement("listen", exact(standard("listen"))),
      requirement("other-language", specializationOf("language-other")),
      requirement("social", socialSelector),
      requirement("psychology", exact(standard("psychology"))),
      requirement("other-skill", anySkill()),
    ],
    "religion-occult",
  ),
  defineOccupation(
    "doctor-of-medicine",
    "医生（原作向）",
    "Doctor of Medicine",
    [
      keeperRulebook(40),
      investigatorHandbook(78, "职业标题始于印刷页 77；机械字段见印刷页 78"),
    ],
    { min: 30, max: 80 },
    edu4,
    [
      requirement("first-aid", exact(standard("first-aid"))),
      requirement("medicine", exact(standard("medicine"))),
      requirement("latin", namedCustomSpecialization("language-other", "拉丁文", "Latin")),
      requirement("psychology", exact(standard("psychology"))),
      requirement("biology", exact(predefined("science", "biology"))),
      requirement("pharmacy", exact(predefined("science", "pharmacy"))),
      requirement(
        "academic-or-personal-specialties",
        anySkill(),
        2,
        2,
        true,
        { zh: "其他学术或个人特长", en: "other academic or personal specialties" },
      ),
    ],
    "medical",
    { aliases: { zh: ["医生", "医师"], en: ["Physician"] } },
  ),
  defineOccupation(
    "elected-official",
    "政府官员",
    "Elected Official",
    [investigatorHandbook(79)],
    { min: 50, max: 90 },
    edu2Plus("APP"),
    [
      requirement("charm", exact(standard("charm"))),
      requirement("history", exact(standard("history"))),
      requirement("intimidate", exact(standard("intimidate"))),
      requirement("fast-talk", exact(standard("fast-talk"))),
      requirement("listen", exact(standard("listen"))),
      requirement("own-language", specializationOf("language-own")),
      requirement("persuade", exact(standard("persuade"))),
      requirement("psychology", exact(standard("psychology"))),
    ],
    "military-government-law",
    { aliases: { zh: ["民选官员"] } },
  ),
  defineOccupation(
    "journalist-keeper-rulebook",
    "记者（核心规则书）",
    "Journalist (Keeper Rulebook)",
    [keeperRulebook(41, "核心规则书记者机械版本")],
    { min: 9, max: 30 },
    edu4,
    [
      requirement("photography", exact(predefined("art-craft", "photography"))),
      requirement("social", socialSelector),
      requirement("history", exact(standard("history"))),
      requirement("library-use", exact(standard("library-use"))),
      requirement("own-language", specializationOf("language-own")),
      requirement("psychology", exact(standard("psychology"))),
      requirement("other-skills", anySkill(), 2, 2),
    ],
    "media-art",
    {
      variantOf: "journalist",
      aliases: { zh: ["记者", "记者（原作向）"], en: ["Journalist"] },
    },
  ),
  defineOccupation(
    "journalist-investigative-handbook",
    "调查记者（调查员手册）",
    "Investigative Journalist (Investigator Handbook)",
    [investigatorHandbook(81, "调查员手册调查记者机械版本")],
    { min: 9, max: 30 },
    edu4,
    [
      requirement("art-or-photography", oneOf(
        exact(predefined("art-craft", "fine-art")),
        exact(predefined("art-craft", "photography")),
      )),
      requirement("social", socialSelector),
      requirement("history", exact(standard("history"))),
      requirement("library-use", exact(standard("library-use"))),
      requirement("own-language", specializationOf("language-own")),
      requirement("psychology", exact(standard("psychology"))),
      requirement("personal-or-era-specialties", anySkill(), 2, 2, true, personalOrEraGuidance),
    ],
    "media-art",
    {
      variantOf: "journalist",
      aliases: { zh: ["记者", "调查记者"], en: ["Investigative Journalist"] },
    },
  ),
  defineOccupation(
    "journalist-reporter-handbook",
    "通讯记者（调查员手册）",
    "Reporter (Investigator Handbook)",
    [investigatorHandbook(81, "技能列表续至印刷页 82；调查员手册通讯记者机械版本")],
    { min: 9, max: 30 },
    edu4,
    [
      requirement("acting", exact(predefined("art-craft", "acting"))),
      requirement("history", exact(standard("history"))),
      requirement("listen", exact(standard("listen"))),
      requirement("own-language", specializationOf("language-own")),
      requirement("social", socialSelector),
      requirement("psychology", exact(standard("psychology"))),
      requirement("stealth", exact(standard("stealth"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
    ],
    "media-art",
    {
      variantOf: "journalist",
      aliases: { zh: ["记者", "通讯记者"], en: ["Reporter"] },
    },
  ),
  defineOccupation(
    "judge",
    "法官",
    "Judge",
    [investigatorHandbook(82)],
    { min: 50, max: 80 },
    edu4,
    [
      requirement("history", exact(standard("history"))),
      requirement("intimidate", exact(standard("intimidate"))),
      requirement("law", exact(standard("law"))),
      requirement("library-use", exact(standard("library-use"))),
      requirement("listen", exact(standard("listen"))),
      requirement("own-language", specializationOf("language-own")),
      requirement("persuade", exact(standard("persuade"))),
      requirement("psychology", exact(standard("psychology"))),
    ],
    "military-government-law",
  ),
  defineOccupation(
    "laboratory-assistant",
    "实验室助理",
    "Laboratory Assistant",
    [investigatorHandbook(82)],
    { min: 10, max: 30 },
    edu4,
    [
      requirement("computer-or-library", oneOf(
        exact(standard("computer-use")),
        exact(standard("library-use")),
      )),
      requirement("electrical-repair", exact(standard("electrical-repair"))),
      requirement("other-language", specializationOf("language-other")),
      requirement("science-set", {
        type: "all-of",
        groups: [
          {
            selector: exact(predefined("science", "chemistry")),
            cardinality: { min: 1, max: 1 },
          },
          {
            selector: specializationOf("science", [predefined("science", "chemistry")]),
            cardinality: { min: 2, max: 2 },
          },
        ],
      }, 3, 3),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement(
        "personal-specialty",
        anySkill(),
        1,
        1,
        true,
        { zh: "其他个人特长", en: "other personal specialty" },
      ),
    ],
    "academic",
  ),
  defineOccupation(
    "museum-curator",
    "博物馆管理员",
    "Museum Curator",
    [investigatorHandbook(84)],
    { min: 10, max: 30 },
    edu4,
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("appraise", exact(standard("appraise"))),
      requirement("archaeology", exact(standard("archaeology"))),
      requirement("history", exact(standard("history"))),
      requirement("library-use", exact(standard("library-use"))),
      requirement("occult", exact(standard("occult"))),
      requirement("other-language", specializationOf("language-other")),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
    ],
    "academic",
    { aliases: { zh: ["博物馆馆长"] } },
  ),
  defineOccupation(
    "police-detective",
    "警探",
    "Police Detective",
    [keeperRulebook(41), investigatorHandbook(87)],
    { min: 20, max: 50 },
    edu2Plus("DEX", "STR"),
    [
      requirement("acting-or-disguise", oneOf(
        exact(predefined("art-craft", "acting")),
        exact(standard("disguise")),
      )),
      requirement("firearms", specializationOf("firearms"), 1, null),
      requirement("law", exact(standard("law"))),
      requirement("listen", exact(standard("listen"))),
      requirement("social", socialSelector),
      requirement("psychology", exact(standard("psychology"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("other-skill", anySkill()),
    ],
    "investigation-security",
    { variantOf: "police", aliases: { zh: ["警探（原作向）"] } },
  ),
  defineOccupation(
    "professor",
    "教授（原作向）",
    "Professor",
    [keeperRulebook(41), investigatorHandbook(87)],
    { min: 20, max: 70 },
    edu4,
    [
      requirement("library-use", exact(standard("library-use"))),
      requirement("other-language", specializationOf("language-other")),
      requirement("own-language", specializationOf("language-own")),
      requirement("psychology", exact(standard("psychology"))),
      requirement(
        "academic-era-personal-specialties",
        anySkill(),
        4,
        4,
        true,
        { zh: "其他学术、时代或个人特长", en: "other academic, era, or personal specialties" },
      ),
    ],
    "academic",
    { aliases: { zh: ["教授"] } },
  ),
  defineOccupation(
    "soldier-marine",
    "士兵、海军陆战队士兵",
    "Soldier / Marine",
    [keeperRulebook(41), investigatorHandbook(89, "技能列表续至印刷页 90")],
    { min: 9, max: 30 },
    edu2Plus("DEX", "STR"),
    [
      requirement("climb-or-swim", oneOf(
        exact(standard("climb")),
        exact(standard("swim")),
      )),
      requirement("dodge", exact(standard("dodge"))),
      requirement("fighting", specializationOf("fighting"), 1, null),
      requirement("firearms", specializationOf("firearms"), 1, null),
      requirement("stealth", exact(standard("stealth"))),
      requirement("survival", specializationOf("survival")),
      requirement("support-skills", oneOf(
        exact(standard("first-aid")),
        exact(standard("mechanical-repair")),
        specializationOf("language-other"),
      ), 2, 2),
    ],
    "military-government-law",
    { aliases: { zh: ["士兵", "海军陆战队士兵"], en: ["Soldier", "Marine"] } },
  ),
  defineOccupation(
    "student-intern",
    "学生、实习生",
    "Student / Intern",
    [investigatorHandbook(90)],
    { min: 5, max: 10 },
    edu4,
    [
      requirement("language", oneOf(
        specializationOf("language-own"),
        specializationOf("language-other"),
      )),
      requirement("library-use", exact(standard("library-use"))),
      requirement("listen", exact(standard("listen"))),
      requirement(
        "study-related-specialties",
        anySkill(),
        3,
        3,
        true,
        { zh: "和学习内容相关的专业技能", en: "specialties related to the course of study" },
      ),
      requirement("personal-or-era-specialties", anySkill(), 2, 2, true, personalOrEraGuidance),
    ],
    "academic",
    { aliases: { zh: ["学生", "实习生"], en: ["Student", "Intern"] } },
  ),
  defineOccupation(
    "missionary-keeper-rulebook",
    "传教士（核心规则书）",
    "Missionary (Keeper Rulebook)",
    [keeperRulebook(41, "职业点公式 EDU×4")],
    { min: 0, max: 30 },
    edu4,
    [
      requirement("art-craft", specializationOf("art-craft")),
      requirement("first-aid", exact(standard("first-aid"))),
      requirement("mechanical-repair", exact(standard("mechanical-repair"))),
      requirement("medicine", exact(standard("medicine"))),
      requirement("natural-world", exact(standard("natural-world"))),
      requirement("social", socialSelector),
      requirement("other-skills", anySkill(), 2, 2),
    ],
    "religion-occult",
    {
      variantOf: "missionary",
      aliases: { zh: ["传教士"], en: ["Missionary"] },
    },
  ),
  defineOccupation(
    "missionary-investigator-handbook",
    "传教士（调查员手册）",
    "Missionary (Investigator Handbook)",
    [investigatorHandbook(83, "职业点公式 EDU×2 + APP×2")],
    { min: 0, max: 30 },
    edu2Plus("APP"),
    [
      requirement("art-craft", specializationOf("art-craft")),
      requirement("first-aid", exact(standard("first-aid"))),
      requirement("mechanical-repair", exact(standard("mechanical-repair"))),
      requirement("medicine", exact(standard("medicine"))),
      requirement("natural-world", exact(standard("natural-world"))),
      requirement("social", socialSelector),
      requirement("personal-or-era-specialties", anySkill(), 2, 2, true, personalOrEraGuidance),
    ],
    "religion-occult",
    {
      variantOf: "missionary",
      aliases: { zh: ["传教士"], en: ["Missionary"] },
    },
  ),
  ...batch2aOccupationDefinitions,
  ...batch2bOccupationDefinitions,
  ...batch2PressureOccupationDefinitions,
  ...batch3aOccupationDefinitions,
];
