import type { WeaponDefinition } from "../../../coc7/types/weapon";

import { defineStandardWeapon, modernOnly, predefined } from "./shared";

const source = {
  keeperPage: 404,
  keeperTable: "表 17 突击步枪",
  investigatorPage: 253,
  investigatorTable: "表 10-6 突击步枪",
};

const rifle = predefined("firearms", "rifle-shotgun");

export const standardAssaultRifles: readonly WeaponDefinition[] = [
  defineStandardWeapon({
    id: "ak-47-akm",
    name: { zh: "AK-47或AKM", en: "AK-47 or AKM" },
    category: "assault-rifle",
    skillRef: rifle,
    damage: "2D6+1",
    impales: true,
    baseRange: "100m",
    attacksPerRound: "1(2)或全自动",
    capacity: "30",
    price: { modern: "$200" },
    malfunction: 100,
    availability: modernOnly,
    source,
  }),
  defineStandardWeapon({
    id: "ak-74",
    name: { zh: "AK-74", en: "AK-74" },
    category: "assault-rifle",
    skillRef: rifle,
    damage: "2D6+1",
    impales: true,
    baseRange: "110m",
    attacksPerRound: "1(2)或全自动",
    capacity: "30",
    price: { modern: "$1000" },
    malfunction: 97,
    availability: modernOnly,
    source: {
      ...source,
      keeperNote: "伤害采用表 17 的 2D6+1",
      investigatorNote: "表 10-6 伤害为 2D6，按 source precedence 不采用",
    },
  }),
  defineStandardWeapon({
    id: "barrett-m82-anti-materiel-rifle",
    name: { zh: "巴雷特M82反器材步枪", en: "Barrett M82 Anti-materiel Rifle" },
    category: "assault-rifle",
    skillRef: rifle,
    damage: "2D10+1D8+6",
    impales: true,
    baseRange: "250m",
    attacksPerRound: "1",
    capacity: "11",
    price: { modern: "$3000" },
    malfunction: 96,
    availability: modernOnly,
    source,
  }),
  defineStandardWeapon({
    id: "fn-fal",
    name: { zh: "FN FAL突击步枪", en: "FN FAL Assault Rifle" },
    category: "assault-rifle",
    skillRef: rifle,
    damage: "2D6+4",
    impales: true,
    baseRange: "110m",
    attacksPerRound: "1(2)或3发点射",
    capacity: "20",
    price: { modern: "$1500" },
    malfunction: 97,
    availability: modernOnly,
    source,
  }),
  defineStandardWeapon({
    id: "galil-assault-rifle",
    name: { zh: "加利尔突击步枪", en: "Galil Assault Rifle" },
    category: "assault-rifle",
    skillRef: rifle,
    damage: "2D6",
    impales: true,
    baseRange: "110m",
    attacksPerRound: "1(2)或全自动",
    capacity: "20",
    price: { modern: "$2000" },
    malfunction: 98,
    availability: modernOnly,
    source,
  }),
  defineStandardWeapon({
    id: "m16a2",
    name: { zh: "M16A2", en: "M16A2" },
    category: "assault-rifle",
    skillRef: rifle,
    damage: "2D6",
    impales: true,
    baseRange: "110m",
    attacksPerRound: "1(2)或3发点射",
    capacity: "30",
    price: { modern: "N/A" },
    malfunction: 97,
    availability: modernOnly,
    source,
  }),
  defineStandardWeapon({
    id: "m4",
    name: { zh: "M4", en: "M4" },
    category: "assault-rifle",
    skillRef: rifle,
    damage: "2D6",
    impales: true,
    baseRange: "90m",
    attacksPerRound: "1或3发点射",
    capacity: "30",
    price: { modern: "N/A" },
    malfunction: 97,
    availability: modernOnly,
    source,
  }),
  defineStandardWeapon({
    id: "steyr-aug",
    name: { zh: "斯太尔AUG", en: "Steyr AUG" },
    category: "assault-rifle",
    skillRef: rifle,
    damage: "2D6",
    impales: true,
    baseRange: "110m",
    attacksPerRound: "1(2)或全自动",
    capacity: "30",
    price: { modern: "$1100" },
    malfunction: 99,
    availability: modernOnly,
    source,
  }),
  defineStandardWeapon({
    id: "beretta-m70-90",
    name: { zh: "贝雷塔M70/90", en: "Beretta M70/90" },
    category: "assault-rifle",
    skillRef: rifle,
    damage: "2D6",
    impales: true,
    baseRange: "110m",
    attacksPerRound: "1或全自动",
    capacity: "30",
    price: { modern: "$2800" },
    malfunction: 99,
    availability: modernOnly,
    source,
  }),
];
