import type { WeaponDefinition } from "../../../coc7/types/weapon";

import {
  availableBoth,
  defineStandardWeapon,
  modernOnly,
  predefined,
  standard,
} from "./shared";

const source = {
  keeperPage: 405,
  keeperTable: "表 17 爆炸物、重武器和其他武器",
  investigatorPage: 254,
  investigatorTable: "表 10-9 爆炸武器、重武器和其他",
};

export const standardExplosiveHeavyOtherWeapons: readonly WeaponDefinition[] = [
  defineStandardWeapon({
    id: "molotov-cocktail",
    name: { zh: "莫洛托夫鸡尾酒", en: "Molotov Cocktail" },
    category: "explosive-heavy-other",
    skillRef: standard("throw"),
    damage: "2D6+燃烧",
    impales: true,
    baseRange: "STR/5m",
    attacksPerRound: "1/2",
    capacity: "一次性",
    price: { classic1920s: "N/A", modern: "N/A" },
    malfunction: 95,
    availability: availableBoth,
    source: {
      ...source,
      keeperNote: "采用公制射程显示",
      investigatorNote: "射程以 STR ft、伤害燃烧简称显示",
    },
  }),
  defineStandardWeapon({
    id: "flare-gun",
    name: { zh: "信号枪", en: "Flare Gun" },
    category: "explosive-heavy-other",
    skillRef: predefined("firearms", "handgun"),
    damage: "1D10+1D3燃烧",
    impales: true,
    baseRange: "10m",
    attacksPerRound: "1/2",
    capacity: "1",
    price: { classic1920s: "$15", modern: "$75" },
    malfunction: 100,
    availability: availableBoth,
    source,
  }),
  defineStandardWeapon({
    id: "m79-grenade-launcher",
    name: { zh: "M79榴弹发射器", en: "M79 Grenade Launcher" },
    category: "explosive-heavy-other",
    skillRef: predefined("firearms", "heavy-weapons"),
    damage: "3D10/2m",
    impales: true,
    baseRange: "20m",
    attacksPerRound: "1/3",
    capacity: "1",
    malfunction: 99,
    availability: modernOnly,
    source: {
      ...source,
      keeperNote: "正式价格单元格为空；采用公制爆心半径",
      investigatorNote: "正式价格单元格同样为空；爆心半径以 2码显示",
    },
  }),
  defineStandardWeapon({
    id: "dynamite-stick",
    name: { zh: "炸药棒", en: "Dynamite Stick" },
    category: "explosive-heavy-other",
    skillRef: standard("throw"),
    damage: "4D10/3m",
    impales: true,
    baseRange: "STR/5m",
    attacksPerRound: "1/2",
    capacity: "一次性",
    price: { classic1920s: "$2", modern: "$5" },
    malfunction: 99,
    availability: availableBoth,
    source: {
      ...source,
      keeperNote: "采用公制射程与爆心半径",
      investigatorNote: "射程以 STR ft、爆心半径以 3码显示",
    },
  }),
  defineStandardWeapon({
    id: "blasting-cap",
    name: { zh: "雷管", en: "Blasting Cap" },
    category: "explosive-heavy-other",
    skillRef: standard("electrical-repair"),
    damage: "2D10/1m",
    impales: true,
    baseRange: "N/A",
    attacksPerRound: "N/A",
    capacity: "一次性",
    price: { classic1920s: "每盒 $1", modern: "每盒 $20" },
    malfunction: 100,
    availability: availableBoth,
    source: {
      ...source,
      keeperNote: "价格采用每盒 $1/$20 显示",
      investigatorNote: "价格显示为 20/整盒",
    },
  }),
  defineStandardWeapon({
    id: "pipe-bomb",
    name: { zh: "管状土制炸弹", en: "Pipe Bomb" },
    category: "explosive-heavy-other",
    skillRef: standard("demolitions"),
    damage: "1D10/3m",
    impales: true,
    baseRange: "原地布设",
    attacksPerRound: "一次性",
    capacity: "一次性",
    price: { classic1920s: "N/A", modern: "N/A" },
    malfunction: 95,
    availability: availableBoth,
    source: {
      ...source,
      keeperNote: "每轮采用表 17 的一次性",
      investigatorNote: "每轮显示为破折号；按 source precedence 不采用",
    },
  }),
  defineStandardWeapon({
    id: "c4-plastic-explosive-100g",
    name: { zh: "塑胶炸弹（C-4）100g／4盎司", en: "C-4 Plastic Explosive (100g / 4 oz.)" },
    category: "explosive-heavy-other",
    skillRef: standard("demolitions"),
    damage: "6D10/3m",
    impales: true,
    baseRange: "原地布设",
    attacksPerRound: "一次性",
    capacity: "一次性",
    price: { modern: "N/A" },
    malfunction: 99,
    availability: modernOnly,
    source: {
      ...source,
      keeperNote: "每轮采用表 17 的一次性",
      investigatorNote: "每轮显示为破折号；按 source precedence 不采用",
    },
  }),
  defineStandardWeapon({
    id: "hand-grenade",
    name: { zh: "手榴弹", en: "Hand Grenade" },
    category: "explosive-heavy-other",
    skillRef: standard("throw"),
    damage: "4D10/3m",
    impales: true,
    baseRange: "STR/5m",
    attacksPerRound: "1/2",
    capacity: "一次性",
    price: { classic1920s: "N/A", modern: "N/A" },
    malfunction: 99,
    availability: availableBoth,
    source: {
      ...source,
      keeperNote: "采用公制射程与爆心半径",
      investigatorNote: "射程以 STR ft、爆心半径以 3码显示",
    },
  }),
  defineStandardWeapon({
    id: "81mm-mortar",
    name: { zh: "81mm迫击炮", en: "81mm Mortar" },
    category: "explosive-heavy-other",
    skillRef: standard("artillery"),
    damage: "6D10/6m",
    impales: true,
    baseRange: "500m",
    attacksPerRound: "1",
    capacity: "独立装弹",
    price: { modern: "N/A" },
    malfunction: 100,
    availability: modernOnly,
    source: {
      ...source,
      keeperNote: "采用公制爆心半径",
      investigatorNote: "爆心半径以 6码显示",
    },
  }),
  defineStandardWeapon({
    id: "75mm-field-gun",
    name: { zh: "75mm野战炮", en: "75mm Field Gun" },
    category: "explosive-heavy-other",
    skillRef: standard("artillery"),
    damage: "10D10/2m",
    impales: true,
    baseRange: "500m",
    attacksPerRound: "1/4",
    capacity: "独立装弹",
    price: { classic1920s: "$1500" },
    malfunction: 99,
    availability: availableBoth,
    source: {
      ...source,
      keeperNote: "采用公制爆心半径",
      investigatorNote: "爆心半径以 2码显示",
    },
  }),
  defineStandardWeapon({
    id: "120mm-tank-gun",
    name: { zh: "120mm坦克炮", en: "120mm Tank Gun" },
    category: "explosive-heavy-other",
    skillRef: standard("artillery"),
    damage: "15D10/2m",
    impales: true,
    baseRange: "2000m",
    attacksPerRound: "1",
    capacity: "独立装弹",
    price: { modern: "N/A" },
    malfunction: 100,
    availability: modernOnly,
    source: {
      ...source,
      keeperNote: "采用公制爆心半径",
      investigatorNote: "爆心半径以 4码显示",
    },
  }),
  defineStandardWeapon({
    id: "5-inch-127mm-naval-gun",
    name: { zh: "5英寸（127mm）舰载炮", en: "5-inch (127mm) Naval Gun" },
    category: "explosive-heavy-other",
    skillRef: standard("artillery"),
    damage: "12D10/4m",
    impales: true,
    baseRange: "3000m",
    attacksPerRound: "1",
    capacity: "自动上弹",
    price: { modern: "N/A" },
    malfunction: 98,
    availability: modernOnly,
    source: {
      ...source,
      keeperNote: "每轮采用表 17 的 1；采用公制爆心半径",
      investigatorNote: "表 10-9 每轮为 2、爆心半径为 4码，按 source precedence 不采用每轮值",
    },
  }),
  defineStandardWeapon({
    id: "anti-personnel-mine",
    name: { zh: "反步兵地雷", en: "Anti-personnel Mine" },
    category: "explosive-heavy-other",
    skillRef: standard("demolitions"),
    damage: "4D10/5m",
    impales: true,
    baseRange: "原地布设",
    attacksPerRound: "布设",
    capacity: "一次性",
    price: { modern: "N/A" },
    malfunction: 99,
    availability: modernOnly,
    source: {
      ...source,
      keeperNote: "每轮采用表 17 的布设；采用公制爆心半径",
      investigatorNote: "每轮显示为破折号、爆心半径以 5码显示",
    },
  }),
  defineStandardWeapon({
    id: "claymore-mine",
    name: { zh: "阔剑地雷", en: "Claymore Mine" },
    category: "explosive-heavy-other",
    skillRef: standard("demolitions"),
    damage: "6D6/20m",
    impales: true,
    baseRange: "原地布设",
    attacksPerRound: "布设",
    capacity: "一次性",
    price: { modern: "N/A" },
    malfunction: 99,
    availability: modernOnly,
    source: {
      ...source,
      keeperNote: "每轮采用表 17 的布设；采用公制杀伤范围",
      investigatorNote: "每轮显示为破折号、杀伤范围以 20码显示",
    },
  }),
  defineStandardWeapon({
    id: "flamethrower",
    name: { zh: "火焰喷射器", en: "Flamethrower" },
    category: "explosive-heavy-other",
    skillRef: predefined("firearms", "flamethrower"),
    damage: "2D6+燃烧",
    impales: true,
    baseRange: "25m",
    attacksPerRound: "1",
    capacity: "至少10",
    price: { classic1920s: "N/A", modern: "N/A" },
    malfunction: 93,
    availability: availableBoth,
    source,
  }),
  defineStandardWeapon({
    id: "m72-light-anti-tank-weapon",
    name: { zh: "M72反坦克火箭筒", en: "M72 Light Anti-tank Weapon" },
    category: "explosive-heavy-other",
    skillRef: predefined("firearms", "heavy-weapons"),
    damage: "8D10/1m",
    impales: true,
    baseRange: "150m",
    attacksPerRound: "1",
    capacity: "1",
    price: { modern: "N/A" },
    malfunction: 98,
    availability: modernOnly,
    source: {
      ...source,
      keeperNote: "采用公制爆心半径",
      investigatorNote: "爆心半径以 1码显示",
    },
  }),
];
