import type { WeaponDefinition } from "../../../coc7/types/weapon";

import {
  availableBoth,
  classicAvailableModernRare,
  classicOnly,
  defineStandardWeapon,
  modernOnly,
  predefined,
  rareBoth,
} from "./shared";

const source = {
  keeperPage: 402,
  keeperTable: "表 17 手枪",
  investigatorPage: 250,
  investigatorTable: "表 10-3 手枪（续至印刷页 251）",
};
const source251 = { ...source, investigatorPage: 251 };

const handgun = predefined("firearms", "handgun");

export const standardHandguns: readonly WeaponDefinition[] = [
  defineStandardWeapon({
    id: "flintlock-pistol",
    name: { zh: "燧发手枪", en: "Flintlock Pistol" },
    category: "handgun",
    skillRef: handgun,
    damage: "1D6+1",
    impales: true,
    baseRange: "10m",
    attacksPerRound: "1/4",
    capacity: "1",
    price: { classic1920s: "$30", modern: "$300" },
    malfunction: 95,
    availability: rareBoth,
    source: {
      ...source,
      keeperNote: "时代单元格仅标稀有，映射为两时代 rare",
      investigatorNote: "时代同样仅标稀有",
    },
  }),
  defineStandardWeapon({
    id: "22-automatic-pistol",
    name: { zh: ".22自动手枪", en: ".22 Automatic Pistol" },
    category: "handgun",
    skillRef: handgun,
    damage: "1D6",
    impales: true,
    baseRange: "10m",
    attacksPerRound: "1(3)",
    capacity: "6",
    price: { classic1920s: "$25", modern: "$190" },
    malfunction: 100,
    availability: availableBoth,
    source,
  }),
  defineStandardWeapon({
    id: "25-derringer-single-barrel",
    name: { zh: ".25德林杰手枪（单管）", en: ".25 Derringer (Single-barrel)" },
    category: "handgun",
    skillRef: handgun,
    damage: "1D6",
    impales: true,
    baseRange: "3m",
    attacksPerRound: "1",
    capacity: "1",
    price: { classic1920s: "$12", modern: "$55" },
    malfunction: 100,
    availability: classicOnly,
    source,
  }),
  defineStandardWeapon({
    id: "32-revolver",
    name: { zh: ".32／7.65mm左轮手枪", en: ".32 / 7.65mm Revolver" },
    category: "handgun",
    skillRef: handgun,
    damage: "1D8",
    impales: true,
    baseRange: "15m",
    attacksPerRound: "1(3)",
    capacity: "6",
    price: { classic1920s: "$15", modern: "$200" },
    malfunction: 100,
    availability: availableBoth,
    source,
  }),
  defineStandardWeapon({
    id: "32-automatic-pistol",
    name: { zh: ".32／7.65mm自动手枪", en: ".32 / 7.65mm Automatic Pistol" },
    category: "handgun",
    skillRef: handgun,
    damage: "1D8",
    impales: true,
    baseRange: "15m",
    attacksPerRound: "1(3)",
    capacity: "8",
    price: { classic1920s: "$20", modern: "$350" },
    malfunction: 99,
    availability: availableBoth,
    source,
  }),
  defineStandardWeapon({
    id: "357-magnum-revolver",
    name: { zh: ".357马格南左轮手枪", en: ".357 Magnum Revolver" },
    category: "handgun",
    skillRef: handgun,
    damage: "1D8+1D4",
    impales: true,
    baseRange: "15m",
    attacksPerRound: "1(3)",
    capacity: "6",
    price: { modern: "$425" },
    malfunction: 100,
    availability: modernOnly,
    source,
  }),
  defineStandardWeapon({
    id: "38-revolver",
    name: { zh: ".38／9mm左轮手枪", en: ".38 / 9mm Revolver" },
    category: "handgun",
    skillRef: handgun,
    damage: "1D10",
    impales: true,
    baseRange: "15m",
    attacksPerRound: "1(3)",
    capacity: "6",
    price: { classic1920s: "$25", modern: "$200" },
    malfunction: 100,
    availability: availableBoth,
    source,
  }),
  defineStandardWeapon({
    id: "38-automatic-pistol",
    name: { zh: ".38／9mm自动手枪", en: ".38 / 9mm Automatic Pistol" },
    category: "handgun",
    skillRef: handgun,
    damage: "1D10",
    impales: true,
    baseRange: "15m",
    attacksPerRound: "1(3)",
    capacity: "8",
    price: { classic1920s: "$30", modern: "$375" },
    malfunction: 99,
    availability: availableBoth,
    source,
  }),
  defineStandardWeapon({
    id: "beretta-m9",
    name: { zh: "贝瑞塔M9", en: "Beretta M9" },
    category: "handgun",
    skillRef: handgun,
    damage: "1D10",
    impales: true,
    baseRange: "15m",
    attacksPerRound: "1(3)",
    capacity: "15",
    price: { modern: "$500" },
    malfunction: 98,
    availability: modernOnly,
    source,
  }),
  defineStandardWeapon({
    id: "glock-17",
    name: { zh: "9mm格洛克17", en: "9mm Glock 17" },
    category: "handgun",
    skillRef: handgun,
    damage: "1D10",
    impales: true,
    baseRange: "15m",
    attacksPerRound: "1(3)",
    capacity: "17",
    price: { modern: "$500" },
    malfunction: 98,
    availability: modernOnly,
    source,
  }),
  defineStandardWeapon({
    id: "luger-p08",
    name: { zh: "9mm鲁格P08", en: "9mm Luger P08" },
    category: "handgun",
    skillRef: handgun,
    damage: "1D10",
    impales: true,
    baseRange: "15m",
    attacksPerRound: "1(3)",
    capacity: "8",
    price: { classic1920s: "$75", modern: "$600" },
    malfunction: 99,
    availability: availableBoth,
    source: source251,
  }),
  defineStandardWeapon({
    id: "41-revolver",
    name: { zh: ".41左轮手枪", en: ".41 Revolver" },
    category: "handgun",
    skillRef: handgun,
    damage: "1D10",
    impales: true,
    baseRange: "15m",
    attacksPerRound: "1(3)",
    capacity: "8",
    price: { classic1920s: "$30" },
    malfunction: 100,
    availability: classicAvailableModernRare,
    source: {
      ...source251,
      keeperNote: "时代为 1920s、稀有，映射为 classic available、modern rare",
      investigatorNote: "时代记为 C稀",
    },
  }),
  defineStandardWeapon({
    id: "44-magnum-revolver",
    name: { zh: ".44马格南左轮手枪", en: ".44 Magnum Revolver" },
    category: "handgun",
    skillRef: handgun,
    damage: "1D10+1D4+2",
    impales: true,
    baseRange: "15m",
    attacksPerRound: "1(3)",
    capacity: "6",
    price: { modern: "$475" },
    malfunction: 100,
    availability: modernOnly,
    source: source251,
  }),
  defineStandardWeapon({
    id: "45-revolver",
    name: { zh: ".45左轮手枪", en: ".45 Revolver" },
    category: "handgun",
    skillRef: handgun,
    damage: "1D10+2",
    impales: true,
    baseRange: "15m",
    attacksPerRound: "1(3)",
    capacity: "6",
    price: { classic1920s: "$30", modern: "$300" },
    malfunction: 100,
    availability: availableBoth,
    source: source251,
  }),
  defineStandardWeapon({
    id: "45-automatic-pistol",
    name: { zh: ".45自动手枪", en: ".45 Automatic Pistol" },
    category: "handgun",
    skillRef: handgun,
    damage: "1D10+2",
    impales: true,
    baseRange: "15m",
    attacksPerRound: "1(3)",
    capacity: "7",
    price: { classic1920s: "$40", modern: "$375" },
    malfunction: 100,
    availability: availableBoth,
    source: source251,
  }),
  defineStandardWeapon({
    id: "imi-desert-eagle",
    name: { zh: "IMI沙漠之鹰", en: "IMI Desert Eagle" },
    category: "handgun",
    skillRef: handgun,
    damage: "1D10+1D6+3",
    impales: true,
    baseRange: "15m",
    attacksPerRound: "1(3)",
    capacity: "7",
    price: { modern: "$650" },
    malfunction: 94,
    availability: modernOnly,
    source: source251,
  }),
];
