import type { WeaponDefinition } from "../../../coc7/types/weapon";

import {
  classicAvailableModernRare,
  classicOnly,
  defineStandardWeapon,
  modernOnly,
  predefined,
} from "./shared";

const source = {
  keeperPage: 404,
  keeperTable: "表 17 机枪",
  investigatorPage: 253,
  investigatorTable: "表 10-8 机枪",
};

const machineGun = predefined("firearms", "machine-gun");

export const standardMachineGuns: readonly WeaponDefinition[] = [
  defineStandardWeapon({
    id: "1882-hand-cranked-gatling-gun",
    name: { zh: "1882年式手摇加特林", en: "1882 Hand-cranked Gatling Gun" },
    category: "machine-gun",
    skillRef: machineGun,
    damage: "2D6+4",
    impales: true,
    baseRange: "100m",
    attacksPerRound: "全自动",
    capacity: "200",
    price: { classic1920s: "$2000", modern: "$14000" },
    malfunction: 96,
    availability: classicAvailableModernRare,
    source: {
      ...source,
      keeperNote: "时代为 1920s、稀有，映射为 classic available、modern rare",
      investigatorNote: "时代记为 C稀",
    },
  }),
  defineStandardWeapon({
    id: "m1918-browning-automatic-rifle",
    name: { zh: "M1918勃朗宁自动步枪", en: "M1918 Browning Automatic Rifle" },
    category: "machine-gun",
    skillRef: machineGun,
    damage: "2D6+4",
    impales: true,
    baseRange: "90m",
    attacksPerRound: "1(2)或全自动",
    capacity: "20",
    price: { classic1920s: "$800", modern: "$1500" },
    malfunction: 100,
    availability: classicOnly,
    source,
  }),
  defineStandardWeapon({
    id: "browning-m1917a1-machine-gun",
    name: { zh: "勃朗宁M1917A1（.30-06／7.62mm）", en: "Browning M1917A1 Machine Gun" },
    category: "machine-gun",
    skillRef: machineGun,
    damage: "2D6+4",
    impales: true,
    baseRange: "150m",
    attacksPerRound: "全自动",
    capacity: "250",
    price: { classic1920s: "$3000", modern: "$3万" },
    malfunction: 96,
    availability: classicOnly,
    source,
  }),
  defineStandardWeapon({
    id: "bren-light-machine-gun",
    name: { zh: "布伦轻机枪", en: "Bren Light Machine Gun" },
    category: "machine-gun",
    skillRef: machineGun,
    damage: "2D6+4",
    impales: true,
    baseRange: "110m",
    attacksPerRound: "1或全自动",
    capacity: "30/100",
    price: { classic1920s: "$3000", modern: "$5万" },
    malfunction: 96,
    availability: classicOnly,
    source,
  }),
  defineStandardWeapon({
    id: "lewis-mark-i-machine-gun",
    name: { zh: "刘易斯MK.I型机枪", en: "Lewis Mark I Machine Gun" },
    category: "machine-gun",
    skillRef: machineGun,
    damage: "2D6+4",
    impales: true,
    baseRange: "110m",
    attacksPerRound: "全自动",
    capacity: "47/97",
    price: { classic1920s: "$3000", modern: "$2万" },
    malfunction: 96,
    availability: classicOnly,
    source: {
      ...source,
      keeperNote: "弹容量采用表 17 的 47/97",
      investigatorNote: "表 10-8 弹数为 27/97，按 source precedence 不采用",
    },
  }),
  defineStandardWeapon({
    id: "rotary-machine-gun-7-62mm",
    name: { zh: "转管速射机枪（7.62mm）", en: "Rotary Machine Gun (7.62mm)" },
    category: "machine-gun",
    skillRef: machineGun,
    damage: "2D6+4",
    impales: true,
    baseRange: "200m",
    attacksPerRound: "全自动",
    capacity: "4000",
    price: { modern: "N/A" },
    malfunction: 98,
    availability: modernOnly,
    source,
  }),
  defineStandardWeapon({
    id: "fn-minimi-machine-gun",
    name: { zh: "FN米尼米机枪（5.56mm）", en: "FN Minimi Machine Gun (5.56mm)" },
    category: "machine-gun",
    skillRef: machineGun,
    damage: "2D6",
    impales: true,
    baseRange: "110m",
    attacksPerRound: "全自动",
    capacity: "30/200",
    price: { modern: "N/A" },
    malfunction: 99,
    availability: modernOnly,
    source,
  }),
  defineStandardWeapon({
    id: "vickers-303-machine-gun",
    name: { zh: "维克斯.303机枪", en: "Vickers .303 Machine Gun" },
    category: "machine-gun",
    skillRef: machineGun,
    damage: "2D6+4",
    impales: true,
    baseRange: "110m",
    attacksPerRound: "全自动",
    capacity: "250",
    price: { classic1920s: "N/A" },
    malfunction: 99,
    availability: classicOnly,
    source,
  }),
];
