import type { WeaponDefinition } from "../../../coc7/types/weapon";

import {
  availableBoth,
  classicOnly,
  defineStandardWeapon,
  modernOnly,
  predefined,
  rareBoth,
  standard,
} from "./shared";

const source = (keeperPage: 401 | 402) => ({
  keeperPage,
  keeperTable: "表 17 常规武器",
  investigatorPage: 250,
  investigatorTable: "表 10-2 近战武器",
});

export const standardMeleeOtherWeapons: readonly WeaponDefinition[] = [
  defineStandardWeapon({
    id: "bow",
    name: { zh: "弓箭", en: "Bow" },
    category: "melee-other",
    skillRef: predefined("firearms", "bow"),
    damage: "1D6+半DB",
    impales: false,
    baseRange: "30m",
    attacksPerRound: "1",
    capacity: "1",
    price: { classic1920s: "$7", modern: "$75" },
    malfunction: 97,
    availability: availableBoth,
    source: {
      ...source(401),
      keeperNote: "采用公制射程显示",
      investigatorNote: "同一射程以 30yd 显示",
    },
  }),
  defineStandardWeapon({
    id: "brass-knuckles",
    name: { zh: "黄铜指虎", en: "Brass Knuckles" },
    category: "melee-other",
    skillRef: predefined("fighting", "brawl"),
    damage: "1D3+1+DB",
    impales: false,
    baseRange: "接触",
    attacksPerRound: "1",
    price: { classic1920s: "$1", modern: "$10" },
    availability: availableBoth,
    source: source(401),
  }),
  defineStandardWeapon({
    id: "bullwhip",
    name: { zh: "长鞭", en: "Bullwhip" },
    category: "melee-other",
    skillRef: predefined("fighting", "whip"),
    damage: "1D3+半DB",
    impales: false,
    baseRange: "3m",
    attacksPerRound: "1",
    price: { classic1920s: "$5", modern: "$50" },
    availability: classicOnly,
    source: {
      ...source(401),
      keeperNote: "采用公制射程显示",
      investigatorNote: "同一射程以 10ft 显示",
    },
  }),
  defineStandardWeapon({
    id: "burning-torch",
    name: { zh: "燃烧的火把", en: "Burning Torch" },
    category: "melee-other",
    skillRef: predefined("fighting", "brawl"),
    damage: "1D6+燃烧",
    impales: false,
    baseRange: "接触",
    attacksPerRound: "1",
    price: { classic1920s: "$0.05", modern: "$0.5" },
    availability: availableBoth,
    source: source(401),
  }),
  defineStandardWeapon({
    id: "chainsaw",
    name: { zh: "链锯", en: "Chainsaw" },
    category: "melee-other",
    skillRef: predefined("fighting", "chainsaw"),
    damage: "2D8",
    impales: true,
    baseRange: "接触",
    attacksPerRound: "1",
    price: { modern: "$300" },
    malfunction: 95,
    availability: modernOnly,
    source: source(401),
  }),
  defineStandardWeapon({
    id: "leather-sap",
    name: { zh: "包革金属棒（大头棍、护身棒）", en: "Leather Sap" },
    category: "melee-other",
    skillRef: predefined("fighting", "brawl"),
    damage: "1D8+DB",
    impales: false,
    baseRange: "接触",
    attacksPerRound: "1",
    price: { classic1920s: "$2", modern: "$15" },
    availability: availableBoth,
    source: source(401),
  }),
  defineStandardWeapon({
    id: "large-club",
    name: { zh: "大型棍棒（棒球棒、板球棒、拨火棍）", en: "Large Club" },
    category: "melee-other",
    skillRef: predefined("fighting", "brawl"),
    damage: "1D8+DB",
    impales: false,
    baseRange: "接触",
    attacksPerRound: "1",
    price: { classic1920s: "$3", modern: "$35" },
    availability: availableBoth,
    source: source(401),
  }),
  defineStandardWeapon({
    id: "small-club",
    name: { zh: "小型棍棒（警棍）", en: "Small Club" },
    category: "melee-other",
    skillRef: predefined("fighting", "brawl"),
    damage: "1D6+DB",
    impales: false,
    baseRange: "接触",
    attacksPerRound: "1",
    price: { classic1920s: "$3", modern: "$35" },
    availability: availableBoth,
    source: source(401),
  }),
  defineStandardWeapon({
    id: "crossbow",
    name: { zh: "弩", en: "Crossbow" },
    category: "melee-other",
    skillRef: predefined("firearms", "bow"),
    damage: "1D8+2",
    impales: true,
    baseRange: "50m",
    attacksPerRound: "1/2",
    capacity: "1",
    price: { classic1920s: "$10", modern: "$100" },
    malfunction: 96,
    availability: availableBoth,
    source: {
      ...source(401),
      keeperNote: "采用公制射程显示",
      investigatorNote: "同一射程以 50yd 显示",
    },
  }),
  defineStandardWeapon({
    id: "garrote",
    name: { zh: "绞索", en: "Garrote" },
    category: "melee-other",
    skillRef: predefined("fighting", "garrote"),
    damage: "1D6+DB",
    impales: true,
    baseRange: "接触",
    attacksPerRound: "1",
    price: { classic1920s: "$0.5", modern: "$3" },
    availability: availableBoth,
    source: source(401),
  }),
  defineStandardWeapon({
    id: "hand-axe-hatchet",
    name: { zh: "手斧／镰刀", en: "Hand Axe / Hatchet" },
    category: "melee-other",
    skillRef: predefined("fighting", "axe"),
    damage: "1D6+1+DB",
    impales: true,
    baseRange: "接触",
    attacksPerRound: "1",
    price: { classic1920s: "$3", modern: "$9" },
    availability: availableBoth,
    source: source(401),
  }),
  defineStandardWeapon({
    id: "large-knife",
    name: { zh: "大型刀（甘蔗刀等）", en: "Large Knife (Machete, etc.)" },
    category: "melee-other",
    skillRef: predefined("fighting", "brawl"),
    damage: "1D8+DB",
    impales: true,
    baseRange: "接触",
    attacksPerRound: "1",
    price: { classic1920s: "$4", modern: "$50" },
    availability: availableBoth,
    source: {
      ...source(401),
      keeperNote: "Keeper 行名为大型刀具（骑兵军刀等）",
      investigatorNote: "沿用 7C-1 的中文显示名",
    },
  }),
  defineStandardWeapon({
    id: "medium-knife",
    name: { zh: "中型刀具（切肉刀等）", en: "Medium Knife" },
    category: "melee-other",
    skillRef: predefined("fighting", "brawl"),
    damage: "1D4+2+DB",
    impales: true,
    baseRange: "接触",
    attacksPerRound: "1",
    price: { classic1920s: "$2", modern: "$15" },
    availability: availableBoth,
    source: source(401),
  }),
  defineStandardWeapon({
    id: "small-knife",
    name: { zh: "小型刀具（折叠刀等）", en: "Small Knife" },
    category: "melee-other",
    skillRef: predefined("fighting", "brawl"),
    damage: "1D4+DB",
    impales: true,
    baseRange: "接触",
    attacksPerRound: "1",
    price: { classic1920s: "$2", modern: "$6" },
    availability: availableBoth,
    source: source(401),
  }),
  defineStandardWeapon({
    id: "220v-live-wire",
    name: { zh: "220V通电导线", en: "220V Live Wire" },
    category: "melee-other",
    skillRef: predefined("fighting", "brawl"),
    damage: "2D8+眩晕",
    impales: false,
    baseRange: "接触",
    attacksPerRound: "1",
    malfunction: 95,
    availability: modernOnly,
    source: source(401),
  }),
  defineStandardWeapon({
    id: "tear-gas-spray",
    name: { zh: "催泪喷雾", en: "Tear Gas Spray" },
    category: "melee-other",
    skillRef: predefined("fighting", "brawl"),
    damage: "晕眩",
    impales: false,
    baseRange: "2m",
    attacksPerRound: "1",
    capacity: "25次喷射",
    price: { modern: "$10" },
    availability: availableBoth,
    source: {
      ...source(401),
      keeperNote: "采用公制射程与晕眩显示",
      investigatorNote: "射程为 6ft，伤害显示为晕",
    },
  }),
  defineStandardWeapon({
    id: "nunchaku",
    name: { zh: "双节棍", en: "Nunchaku" },
    category: "melee-other",
    skillRef: predefined("fighting", "flail"),
    damage: "1D8+DB",
    impales: false,
    baseRange: "接触",
    attacksPerRound: "1",
    price: { classic1920s: "$1", modern: "$10" },
    availability: availableBoth,
    source: source(401),
  }),
  defineStandardWeapon({
    id: "thrown-rock",
    name: { zh: "投石", en: "Thrown Rock" },
    category: "melee-other",
    skillRef: standard("throw"),
    damage: "1D4+半DB",
    impales: false,
    baseRange: "STR ft",
    attacksPerRound: "1",
    availability: availableBoth,
    source: {
      ...source(401),
      keeperNote: "Keeper 公制显示为 STR/5m",
      investigatorNote: "沿用 7C-1 的 STR ft 显示",
    },
  }),
  defineStandardWeapon({
    id: "shuriken",
    name: { zh: "手里剑", en: "Shuriken" },
    category: "melee-other",
    skillRef: standard("throw"),
    damage: "1D3+半DB",
    impales: true,
    baseRange: "STR/5m",
    attacksPerRound: "2",
    capacity: "一次性",
    price: { classic1920s: "$0.5", modern: "$3" },
    malfunction: 100,
    availability: availableBoth,
    source: {
      ...source(401),
      keeperNote: "采用公制射程显示",
      investigatorNote: "同一射程以接触显示",
    },
  }),
  defineStandardWeapon({
    id: "lance",
    name: { zh: "矛（骑枪）", en: "Lance" },
    category: "melee-other",
    skillRef: predefined("fighting", "spear"),
    damage: "1D8+1",
    impales: true,
    baseRange: "接触",
    attacksPerRound: "1",
    price: { classic1920s: "$25", modern: "$150" },
    availability: availableBoth,
    source: source(402),
  }),
  defineStandardWeapon({
    id: "thrown-spear",
    name: { zh: "投矛", en: "Thrown Spear" },
    category: "melee-other",
    skillRef: standard("throw"),
    damage: "1D8+半DB",
    impales: true,
    baseRange: "STR/5m",
    attacksPerRound: "1",
    price: { classic1920s: "$1", modern: "$25" },
    availability: rareBoth,
    source: {
      ...source(402),
      keeperNote: "时代单元格仅标稀有，映射为两时代 rare",
      investigatorNote: "时代同样仅标稀有；射程以 STR yd 显示",
    },
  }),
  defineStandardWeapon({
    id: "large-sword",
    name: { zh: "大型刀剑（马刀）", en: "Large Sword" },
    category: "melee-other",
    skillRef: predefined("fighting", "sword"),
    damage: "1D8+1+DB",
    impales: true,
    baseRange: "接触",
    attacksPerRound: "1",
    price: { classic1920s: "$30", modern: "$75" },
    availability: availableBoth,
    source: source(402),
  }),
  defineStandardWeapon({
    id: "medium-sword",
    name: { zh: "中型刀剑（长剑、重剑）", en: "Medium Sword" },
    category: "melee-other",
    skillRef: predefined("fighting", "sword"),
    damage: "1D6+1+DB",
    impales: true,
    baseRange: "接触",
    attacksPerRound: "1",
    price: { classic1920s: "$15", modern: "$100" },
    availability: availableBoth,
    source: source(402),
  }),
  defineStandardWeapon({
    id: "light-sword",
    name: { zh: "轻型刀剑（花剑、剑杖）", en: "Light Sword" },
    category: "melee-other",
    skillRef: predefined("fighting", "sword"),
    damage: "1D6+DB",
    impales: true,
    baseRange: "接触",
    attacksPerRound: "1",
    price: { classic1920s: "$25", modern: "$100" },
    availability: availableBoth,
    source: source(402),
  }),
  defineStandardWeapon({
    id: "stun-gun",
    name: { zh: "电击器", en: "Stun Gun" },
    category: "melee-other",
    skillRef: predefined("fighting", "brawl"),
    damage: "1D3+晕眩",
    impales: false,
    baseRange: "接触",
    attacksPerRound: "1",
    capacity: "可变",
    price: { modern: "$200" },
    malfunction: 97,
    availability: modernOnly,
    source: source(402),
  }),
  defineStandardWeapon({
    id: "taser",
    name: { zh: "泰瑟枪", en: "Taser" },
    category: "melee-other",
    skillRef: predefined("firearms", "handgun"),
    damage: "1D3+晕眩",
    impales: false,
    baseRange: "5m",
    attacksPerRound: "1",
    capacity: "3",
    price: { modern: "$400" },
    malfunction: 95,
    availability: modernOnly,
    source: {
      ...source(402),
      keeperNote: "采用射击（手枪）行",
      investigatorNote: "表中同时列接触与射击两种电击枪；本行对应射击版本",
    },
  }),
  defineStandardWeapon({
    id: "combat-boomerang",
    name: { zh: "战斗回力镖", en: "Combat Boomerang" },
    category: "melee-other",
    skillRef: standard("throw"),
    damage: "1D8+半DB",
    impales: false,
    baseRange: "STR/5m",
    attacksPerRound: "1",
    price: { classic1920s: "$2", modern: "$4" },
    availability: rareBoth,
    source: {
      ...source(402),
      keeperNote: "时代单元格仅标稀有，映射为两时代 rare",
      investigatorNote: "时代同样仅标稀有；射程以 20yd 显示",
    },
  }),
  defineStandardWeapon({
    id: "wood-axe",
    name: { zh: "伐木斧", en: "Wood Axe" },
    category: "melee-other",
    skillRef: predefined("fighting", "axe"),
    damage: "1D8+2+DB",
    impales: true,
    baseRange: "接触",
    attacksPerRound: "1",
    price: { classic1920s: "$5", modern: "$10" },
    availability: availableBoth,
    source: source(402),
  }),
];
