import type { WeaponDefinition } from "../../../coc7/types/weapon";

import {
  availableBoth,
  classicOnly,
  defineStandardWeapon,
  modernOnly,
  predefined,
  rareBoth,
} from "./shared";

const source = {
  keeperPage: 403,
  keeperTable: "表 17 步枪",
  investigatorPage: 252,
  investigatorTable: "表 10-4 步枪",
};

const rifle = predefined("firearms", "rifle-shotgun");

export const standardRifles: readonly WeaponDefinition[] = [
  defineStandardWeapon({
    id: "58-springfield-flintlock-rifle",
    name: { zh: ".58春田燧发步枪", en: ".58 Springfield Flintlock Rifle" },
    category: "rifle",
    skillRef: rifle,
    damage: "1D10+4",
    impales: true,
    baseRange: "60m",
    attacksPerRound: "1/4",
    capacity: "1",
    price: { classic1920s: "$25", modern: "$350" },
    malfunction: 95,
    availability: rareBoth,
    source: {
      ...source,
      keeperNote: "时代单元格仅标稀有，映射为两时代 rare",
      investigatorNote: "时代同样仅标稀有",
    },
  }),
  defineStandardWeapon({
    id: "22-bolt-action-rifle",
    name: { zh: ".22栓动步枪", en: ".22 Bolt-action Rifle" },
    category: "rifle",
    skillRef: rifle,
    damage: "1D6+1",
    impales: true,
    baseRange: "30m",
    attacksPerRound: "1",
    capacity: "6",
    price: { classic1920s: "$13", modern: "$70" },
    malfunction: 99,
    availability: availableBoth,
    source,
  }),
  defineStandardWeapon({
    id: "30-lever-action-rifle",
    name: { zh: ".30杠杆步枪", en: ".30 Lever-action Rifle" },
    category: "rifle",
    skillRef: rifle,
    damage: "2D6",
    impales: true,
    baseRange: "50m",
    attacksPerRound: "1",
    capacity: "6",
    price: { classic1920s: "$19", modern: "$150" },
    malfunction: 98,
    availability: availableBoth,
    source,
  }),
  defineStandardWeapon({
    id: "45-martini-henry-rifle",
    name: { zh: ".45马蒂尼-亨利步枪", en: ".45 Martini-Henry Rifle" },
    category: "rifle",
    skillRef: rifle,
    damage: "1D8+1D6+3",
    impales: true,
    baseRange: "80m",
    attacksPerRound: "1/3",
    capacity: "1",
    price: { classic1920s: "$20", modern: "$200" },
    malfunction: 100,
    availability: classicOnly,
    source,
  }),
  defineStandardWeapon({
    id: "colonel-morans-air-rifle",
    name: { zh: "莫兰上校的气动步枪", en: "Colonel Moran's Air Rifle" },
    category: "rifle",
    skillRef: rifle,
    damage: "2D6+1",
    impales: true,
    baseRange: "20m",
    attacksPerRound: "1/3",
    capacity: "1",
    price: { classic1920s: "$200" },
    malfunction: 88,
    availability: classicOnly,
    source,
  }),
  defineStandardWeapon({
    id: "m1-m2-garand-rifle",
    name: { zh: "加兰德M1、M2步枪", en: "M1 / M2 Garand Rifle" },
    category: "rifle",
    skillRef: rifle,
    damage: "2D6+4",
    impales: true,
    baseRange: "110m",
    attacksPerRound: "1",
    capacity: "8",
    price: { modern: "$400" },
    malfunction: 100,
    availability: modernOnly,
    source: {
      ...source,
      keeperNote: "二战及以后映射为 classic unavailable、modern available",
      investigatorNote: "同样标为二战及以后",
    },
  }),
  defineStandardWeapon({
    id: "sks-semi-automatic-rifle",
    name: { zh: "SKS半自动步枪", en: "SKS Semi-automatic Rifle" },
    category: "rifle",
    skillRef: rifle,
    damage: "2D6+1",
    impales: true,
    baseRange: "90m",
    attacksPerRound: "1(2)",
    capacity: "10",
    price: { modern: "$500" },
    malfunction: 97,
    availability: modernOnly,
    source,
  }),
  defineStandardWeapon({
    id: "303-lee-enfield-rifle",
    name: { zh: ".303李-恩菲尔德步枪", en: ".303 Lee-Enfield Rifle" },
    category: "rifle",
    skillRef: rifle,
    damage: "2D6+4",
    impales: true,
    baseRange: "110m",
    attacksPerRound: "1",
    capacity: "10",
    price: { classic1920s: "$50", modern: "$300" },
    malfunction: 100,
    availability: availableBoth,
    source: {
      ...source,
      keeperNote: "弹容量采用表 17 的 10",
      investigatorNote: "表 10-4 弹数为 5，按 source precedence 不采用",
    },
  }),
  defineStandardWeapon({
    id: "30-06-bolt-action-rifle",
    name: { zh: ".30-06（7.62mm）栓动步枪", en: ".30-06 (7.62mm) Bolt-action Rifle" },
    category: "rifle",
    skillRef: rifle,
    damage: "2D6+4",
    impales: true,
    baseRange: "110m",
    attacksPerRound: "1",
    capacity: "5",
    price: { classic1920s: "$75", modern: "$175" },
    malfunction: 100,
    availability: availableBoth,
    source,
  }),
  defineStandardWeapon({
    id: "30-06-semi-automatic-rifle",
    name: { zh: ".30-06（7.62mm）半自动步枪", en: ".30-06 (7.62mm) Semi-automatic Rifle" },
    category: "rifle",
    skillRef: rifle,
    damage: "2D6+4",
    impales: true,
    baseRange: "110m",
    attacksPerRound: "1",
    capacity: "5",
    price: { modern: "$275" },
    malfunction: 100,
    availability: modernOnly,
    source,
  }),
  defineStandardWeapon({
    id: "444-marlin-lever-action-rifle",
    name: { zh: ".444马林杠杆步枪", en: ".444 Marlin Lever-action Rifle" },
    category: "rifle",
    skillRef: rifle,
    damage: "2D8+4",
    impales: true,
    baseRange: "110m",
    attacksPerRound: "1",
    capacity: "5",
    price: { modern: "$400" },
    malfunction: 98,
    availability: modernOnly,
    source,
  }),
  defineStandardWeapon({
    id: "double-barrel-elephant-gun",
    name: { zh: "双管猎象枪", en: "Double-barrel Elephant Gun" },
    category: "rifle",
    skillRef: rifle,
    damage: "3D6+4",
    impales: true,
    baseRange: "100m",
    attacksPerRound: "1或2",
    capacity: "2",
    price: { classic1920s: "$400", modern: "$1800" },
    malfunction: 100,
    availability: availableBoth,
    source: {
      ...source,
      keeperNote: "现代价格采用表 17 的 $1800",
      investigatorNote: "表 10-4 现代价格为 $1000，按 source precedence 不采用",
    },
  }),
];
