import type { WeaponDefinition } from "../../../coc7/types/weapon";

import {
  availableBoth,
  classicOnly,
  classicRareOnly,
  defineStandardWeapon,
  modernOnly,
  predefined,
} from "./shared";

const source = {
  keeperPage: 403,
  keeperTable: "表 17 霰弹枪",
  investigatorPage: 252,
  investigatorTable: "表 10-5 霰弹枪",
};

const shotgun = predefined("firearms", "rifle-shotgun");

export const standardShotguns: readonly WeaponDefinition[] = [
  defineStandardWeapon({
    id: "20-gauge-double-barrel-shotgun",
    name: { zh: "20号双管霰弹枪", en: "20-gauge Double-barrel Shotgun" },
    category: "shotgun",
    skillRef: shotgun,
    damage: "2D6/1D6/1D3",
    impales: false,
    baseRange: "10/20/50m",
    attacksPerRound: "1或2",
    capacity: "2",
    price: { classic1920s: "$35", modern: "稀有" },
    malfunction: 100,
    availability: classicOnly,
    source,
  }),
  defineStandardWeapon({
    id: "16-gauge-double-barrel-shotgun",
    name: { zh: "16号双管霰弹枪", en: "16-gauge Double-barrel Shotgun" },
    category: "shotgun",
    skillRef: shotgun,
    damage: "2D6+2/1D6+1/1D4",
    impales: false,
    baseRange: "10/20/50m",
    attacksPerRound: "1或2",
    capacity: "2",
    price: { classic1920s: "$40", modern: "稀有" },
    malfunction: 100,
    availability: classicOnly,
    source,
  }),
  defineStandardWeapon({
    id: "12-gauge-double-barrel-shotgun",
    name: { zh: "12号双管霰弹枪", en: "12-gauge Double-barrel Shotgun" },
    category: "shotgun",
    skillRef: shotgun,
    damage: "4D6/2D6/1D6",
    impales: false,
    baseRange: "10/20/50m",
    attacksPerRound: "1或2",
    capacity: "2",
    price: { classic1920s: "$40", modern: "$200" },
    malfunction: 100,
    availability: availableBoth,
    source,
  }),
  defineStandardWeapon({
    id: "12-gauge-pump-action-shotgun",
    name: { zh: "12号泵动式霰弹枪", en: "12-gauge Pump-action Shotgun" },
    category: "shotgun",
    skillRef: shotgun,
    damage: "4D6/2D6/1D6",
    impales: false,
    baseRange: "10/20/50m",
    attacksPerRound: "1",
    capacity: "5",
    price: { classic1920s: "$45", modern: "$100" },
    malfunction: 100,
    availability: modernOnly,
    source,
  }),
  defineStandardWeapon({
    id: "12-gauge-semi-automatic-shotgun",
    name: { zh: "12号半自动霰弹枪", en: "12-gauge Semi-automatic Shotgun" },
    category: "shotgun",
    skillRef: shotgun,
    damage: "4D6/2D6/1D6",
    impales: false,
    baseRange: "10/20/50m",
    attacksPerRound: "1(2)",
    capacity: "5",
    price: { classic1920s: "$45", modern: "$100" },
    malfunction: 100,
    availability: modernOnly,
    source,
  }),
  defineStandardWeapon({
    id: "12-gauge-sawed-off-double-barrel-shotgun",
    name: { zh: "12号双管霰弹枪（锯短枪管）", en: "12-gauge Sawed-off Double-barrel Shotgun" },
    category: "shotgun",
    skillRef: shotgun,
    damage: "4D6/1D6",
    impales: false,
    baseRange: "5/10m",
    attacksPerRound: "1或2",
    capacity: "2",
    price: { classic1920s: "N/A" },
    malfunction: 100,
    availability: classicOnly,
    source,
  }),
  defineStandardWeapon({
    id: "10-gauge-double-barrel-shotgun",
    name: { zh: "10号双管霰弹枪", en: "10-gauge Double-barrel Shotgun" },
    category: "shotgun",
    skillRef: shotgun,
    damage: "4D6+2/2D6+1/1D4",
    impales: false,
    baseRange: "10/20/50m",
    attacksPerRound: "1或2",
    capacity: "2",
    price: { classic1920s: "稀有" },
    malfunction: 100,
    availability: classicRareOnly,
    source: {
      ...source,
      keeperNote: "时代显示为 1920s稀有，映射为 classic rare、modern unavailable",
      investigatorNote: "时代记为 C稀",
    },
  }),
  defineStandardWeapon({
    id: "12-gauge-benelli-m3-folding-stock",
    name: { zh: "12号伯奈利M3霰弹枪（折叠枪托）", en: "12-gauge Benelli M3 (Folding Stock)" },
    category: "shotgun",
    skillRef: shotgun,
    damage: "4D6/2D6/1D6",
    impales: false,
    baseRange: "10/20/50m",
    attacksPerRound: "1(2)",
    capacity: "7",
    price: { modern: "$895" },
    malfunction: 100,
    availability: modernOnly,
    source,
  }),
  defineStandardWeapon({
    id: "12-gauge-spas-folding-stock",
    name: { zh: "12号SPAS霰弹枪（折叠枪托）", en: "12-gauge SPAS (Folding Stock)" },
    category: "shotgun",
    skillRef: shotgun,
    damage: "4D6/2D6/1D6",
    impales: false,
    baseRange: "10/20/50m",
    attacksPerRound: "1",
    capacity: "8",
    price: { modern: "$600" },
    malfunction: 98,
    availability: modernOnly,
    source,
  }),
];
