import type { WeaponDefinition } from "../../../coc7/types/weapon";

import { classicOnly, defineStandardWeapon, modernOnly, predefined } from "./shared";

const source = {
  keeperPage: 404,
  keeperTable: "表 17 冲锋枪",
  investigatorPage: 253,
  investigatorTable: "表 10-7 冲锋枪",
};

const submachineGun = predefined("firearms", "submachine-gun");

export const standardSubmachineGuns: readonly WeaponDefinition[] = [
  defineStandardWeapon({
    id: "bergmann-mp18-mp28",
    name: { zh: "贝格曼MP18I／MP28II", en: "Bergmann MP18I / MP28II" },
    category: "submachine-gun",
    skillRef: submachineGun,
    damage: "1D10",
    impales: true,
    baseRange: "20m",
    attacksPerRound: "1(2)或全自动",
    capacity: "20/30/32",
    price: { classic1920s: "$1000", modern: "$20000" },
    malfunction: 96,
    availability: classicOnly,
    source: {
      ...source,
      keeperNote: "型号字形按 MP18I／MP28II 规范显示",
      investigatorNote: "表 10-7 同行",
    },
  }),
  defineStandardWeapon({
    id: "hk-mp5",
    name: { zh: "H&K MP5", en: "H&K MP5" },
    category: "submachine-gun",
    skillRef: submachineGun,
    damage: "1D10",
    impales: true,
    baseRange: "20m",
    attacksPerRound: "1(2)或全自动",
    capacity: "15/30",
    price: { modern: "N/A" },
    malfunction: 97,
    availability: modernOnly,
    source,
  }),
  defineStandardWeapon({
    id: "mac-11",
    name: { zh: "MAC-11", en: "MAC-11" },
    category: "submachine-gun",
    skillRef: submachineGun,
    damage: "1D10",
    impales: true,
    baseRange: "15m",
    attacksPerRound: "1(3)或全自动",
    capacity: "32",
    price: { modern: "$750" },
    malfunction: 96,
    availability: modernOnly,
    source,
  }),
  defineStandardWeapon({
    id: "skorpion-submachine-gun",
    name: { zh: "蝎式冲锋枪", en: "Skorpion Submachine Gun" },
    category: "submachine-gun",
    skillRef: submachineGun,
    damage: "1D8",
    impales: true,
    baseRange: "15m",
    attacksPerRound: "1(3)或全自动",
    capacity: "20",
    price: { modern: "N/A" },
    malfunction: 96,
    availability: modernOnly,
    source,
  }),
  defineStandardWeapon({
    id: "thompson-submachine-gun",
    name: { zh: "汤普森冲锋枪", en: "Thompson Submachine Gun" },
    category: "submachine-gun",
    skillRef: submachineGun,
    damage: "1D10+2",
    impales: true,
    baseRange: "20m",
    attacksPerRound: "1或全自动",
    capacity: "20/30/50",
    price: { classic1920s: "$200+", modern: "$1600" },
    malfunction: 96,
    availability: classicOnly,
    source,
  }),
  defineStandardWeapon({
    id: "uzi-submachine-gun",
    name: { zh: "乌兹冲锋枪", en: "Uzi Submachine Gun" },
    category: "submachine-gun",
    skillRef: submachineGun,
    damage: "1D10",
    impales: true,
    baseRange: "20m",
    attacksPerRound: "1(2)或全自动",
    capacity: "32",
    price: { modern: "$1000" },
    malfunction: 98,
    availability: modernOnly,
    source,
  }),
];
