import type { OccupationDefinition } from "../../../coc7/types/occupation";

import {
  anySkill,
  choicePool,
  defineOccupation,
  edu2Plus,
  edu4,
  exact,
  investigatorHandbook,
  keeperRulebook,
  oneBranch,
  oneOf,
  personalOrEraGuidance,
  predefined,
  requirement,
  socialSelector,
  specializationOf,
  standard,
} from "./shared";

const genericFighting = specializationOf("fighting");
const genericFirearms = specializationOf("firearms");
const acting = exact(predefined("art-craft", "acting"));
const forgery = exact(predefined("art-craft", "forgery"));
const brawl = exact(predefined("fighting", "brawl"));
const handgun = exact(predefined("firearms", "handgun"));

export const batch3eCriminalOccupationDefinitions: readonly OccupationDefinition[] = [
  defineOccupation(
    "criminal-keeper-rulebook",
    "罪犯",
    "Criminal",
    [keeperRulebook(40)],
    { min: 5, max: 65 },
    edu2Plus("DEX", "STR"),
    [
      requirement("social", socialSelector),
      requirement("stealth", exact(standard("stealth"))),
      requirement("psychology", exact(standard("psychology"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("criminal-specialties", choicePool(
        { min: 4, max: 4 },
        { selector: genericFighting, cardinality: { min: 1 } },
        { selector: exact(standard("appraise")), cardinality: { min: 1, max: 1 } },
        { selector: exact(standard("mechanical-repair")), cardinality: { min: 1, max: 1 } },
        { selector: exact(standard("sleight-of-hand")), cardinality: { min: 1, max: 1 } },
        { selector: exact(standard("disguise")), cardinality: { min: 1, max: 1 } },
        { selector: genericFirearms, cardinality: { min: 1 } },
        { selector: exact(standard("locksmith")), cardinality: { min: 1, max: 1 } },
      ), 4, null),
    ],
    "criminal-underworld",
    { variantOf: "criminal" },
  ),
  defineOccupation(
    "criminal-assassin",
    "刺客",
    "Assassin",
    [investigatorHandbook(75)],
    { min: 30, max: 60 },
    edu2Plus("DEX", "STR"),
    [
      requirement("disguise", exact(standard("disguise"))),
      requirement("electrical-repair", exact(standard("electrical-repair"))),
      requirement("fighting", genericFighting, 1, null),
      requirement("firearms", genericFirearms, 1, null),
      requirement("locksmith", exact(standard("locksmith"))),
      requirement("mechanical-repair", exact(standard("mechanical-repair"))),
      requirement("stealth", exact(standard("stealth"))),
      requirement("psychology", exact(standard("psychology"))),
    ],
    "criminal-underworld",
    { variantOf: "criminal" },
  ),
  defineOccupation(
    "criminal-bank-robber",
    "银行劫匪",
    "Bank Robber",
    [investigatorHandbook(75)],
    { min: 5, max: 75 },
    edu2Plus("DEX", "STR"),
    [
      requirement("drive-auto", exact(standard("drive-auto"))),
      requirement("electrical-or-mechanical-repair", oneOf(
        exact(standard("electrical-repair")),
        exact(standard("mechanical-repair")),
      )),
      requirement("fighting", genericFighting, 1, null),
      requirement("firearms", genericFirearms, 1, null),
      requirement("intimidate", exact(standard("intimidate"))),
      requirement("locksmith", exact(standard("locksmith"))),
      requirement("operate-heavy-machinery", exact(standard("operate-heavy-machinery"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "criminal-underworld",
    { variantOf: "criminal" },
  ),
  defineOccupation(
    "criminal-bootlegger-thug",
    "打手、暴徒",
    "Bootlegger / Thug",
    [investigatorHandbook(75)],
    { min: 5, max: 30 },
    edu2Plus("STR"),
    [
      requirement("drive-auto", exact(standard("drive-auto"))),
      requirement("fighting", genericFighting, 1, null),
      requirement("firearms", genericFirearms, 1, null),
      requirement("social", socialSelector, 2, 2),
      requirement("psychology", exact(standard("psychology"))),
      requirement("stealth", exact(standard("stealth"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
    ],
    "criminal-underworld",
    { variantOf: "criminal" },
  ),
  defineOccupation(
    "criminal-burglar",
    "窃贼",
    "Burglar",
    [investigatorHandbook(75)],
    { min: 5, max: 40 },
    edu2Plus("DEX"),
    [
      requirement("appraise", exact(standard("appraise"))),
      requirement("climb", exact(standard("climb"))),
      requirement("electrical-or-mechanical-repair", oneOf(
        exact(standard("electrical-repair")),
        exact(standard("mechanical-repair")),
      )),
      requirement("listen", exact(standard("listen"))),
      requirement("locksmith", exact(standard("locksmith"))),
      requirement("sleight-of-hand", exact(standard("sleight-of-hand"))),
      requirement("stealth", exact(standard("stealth"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
    ],
    "criminal-underworld",
    { variantOf: "criminal" },
  ),
  defineOccupation(
    "criminal-conman",
    "欺诈师",
    "Conman",
    [investigatorHandbook(75)],
    { min: 10, max: 65 },
    edu2Plus("APP"),
    [
      requirement("appraise", exact(standard("appraise"))),
      requirement("acting", acting),
      requirement("law-or-other-language", oneOf(
        exact(standard("law")),
        specializationOf("language-other"),
      )),
      requirement("listen", exact(standard("listen"))),
      requirement("social", socialSelector, 2, 2),
      requirement("psychology", exact(standard("psychology"))),
      requirement("sleight-of-hand", exact(standard("sleight-of-hand"))),
    ],
    "criminal-underworld",
    { variantOf: "criminal" },
  ),
  defineOccupation(
    "criminal-freelance-solo",
    "独行罪犯",
    "Criminal (Freelance / Solo)",
    [investigatorHandbook(75)],
    { min: 5, max: 65 },
    edu2Plus("APP", "DEX"),
    [
      requirement("acting-or-disguise", oneOf(
        acting,
        exact(standard("disguise")),
      )),
      requirement("appraise", exact(standard("appraise"))),
      requirement("social", socialSelector),
      requirement("fighting-or-firearms", oneBranch(
        { selector: genericFighting, cardinality: { min: 1 } },
        { selector: genericFirearms, cardinality: { min: 1 } },
      ), 1, null),
      requirement("locksmith-or-mechanical-repair", oneOf(
        exact(standard("locksmith")),
        exact(standard("mechanical-repair")),
      )),
      requirement("stealth", exact(standard("stealth"))),
      requirement("psychology", exact(standard("psychology"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
    ],
    "criminal-underworld",
    { variantOf: "criminal" },
  ),
  defineOccupation(
    "criminal-gun-moll",
    "女飞贼（古典）",
    "Gun Moll",
    [investigatorHandbook(76, "信用范围旁注说明收入很大程度上取决于男伴收入")],
    { min: 10, max: 80 },
    edu2Plus("APP"),
    [
      requirement("art-craft", specializationOf("art-craft")),
      requirement("social", socialSelector, 2, 2),
      requirement("brawl-or-handgun", oneOf(brawl, handgun)),
      requirement("drive-auto", exact(standard("drive-auto"))),
      requirement("listen", exact(standard("listen"))),
      requirement("stealth", exact(standard("stealth"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "criminal-underworld",
    {
      variantOf: "criminal",
      era: { type: "specific", eraIds: ["classic-1920s"] },
    },
  ),
  defineOccupation(
    "criminal-fence",
    "赃物贩子",
    "Fence",
    [investigatorHandbook(76)],
    { min: 20, max: 40 },
    edu2Plus("APP"),
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("appraise", exact(standard("appraise"))),
      requirement("forgery", forgery),
      requirement("history", exact(standard("history"))),
      requirement("social", socialSelector),
      requirement("library-use", exact(standard("library-use"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("other-skill", anySkill()),
    ],
    "criminal-underworld",
    { variantOf: "criminal" },
  ),
  defineOccupation(
    "criminal-forger-counterfeiter",
    "赝造者、伪造者",
    "Forger / Counterfeiter",
    [investigatorHandbook(76)],
    { min: 20, max: 60 },
    edu4,
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("appraise", exact(standard("appraise"))),
      requirement("forgery", forgery),
      requirement("history", exact(standard("history"))),
      requirement("library-use", exact(standard("library-use"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("sleight-of-hand", exact(standard("sleight-of-hand"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "criminal-underworld",
    { variantOf: "criminal" },
  ),
  defineOccupation(
    "criminal-smuggler",
    "走私者",
    "Smuggler",
    [investigatorHandbook(76)],
    { min: 20, max: 60 },
    edu2Plus("APP", "DEX"),
    [
      requirement("firearms", genericFirearms, 1, null),
      requirement("listen", exact(standard("listen"))),
      requirement("navigate", exact(standard("navigate"))),
      requirement("social", socialSelector),
      requirement("transport", oneOf(
        exact(standard("drive-auto")),
        exact(predefined("pilot", "aircraft")),
        exact(predefined("pilot", "boat")),
      )),
      requirement("psychology", exact(standard("psychology"))),
      requirement("sleight-of-hand", exact(standard("sleight-of-hand"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
    ],
    "criminal-underworld",
    { variantOf: "criminal" },
  ),
  defineOccupation(
    "criminal-street-punk",
    "混混",
    "Street Punk",
    [investigatorHandbook(76)],
    { min: 3, max: 10 },
    edu2Plus("DEX", "STR"),
    [
      requirement("climb", exact(standard("climb"))),
      requirement("social", socialSelector),
      requirement("fighting", genericFighting, 1, null),
      requirement("firearms", genericFirearms, 1, null),
      requirement("jump", exact(standard("jump"))),
      requirement("sleight-of-hand", exact(standard("sleight-of-hand"))),
      requirement("stealth", exact(standard("stealth"))),
      requirement("throw", exact(standard("throw"))),
    ],
    "criminal-underworld",
    { variantOf: "criminal" },
  ),
];
