import type { OccupationDefinition } from "../../../coc7/types/occupation";

import {
  anySkill,
  defineOccupation,
  edu2Plus,
  edu4,
  exact,
  investigatorHandbook,
  keeperRulebook,
  namedCustomSpecialization,
  oneOf,
  personalOrEraGuidance,
  predefined,
  requirement,
  socialSelector,
  specializationOf,
  standard,
} from "./shared";

const brawl = exact(predefined("fighting", "brawl"));
const genericFirearms = specializationOf("firearms");

const personalSpecialtyGuidance = {
  zh: "个人特长",
  en: "personal specialty",
};

export const batch3aOccupationDefinitions: readonly OccupationDefinition[] = [
  defineOccupation(
    "acrobat",
    "杂技演员",
    "Acrobat",
    [investigatorHandbook(70)],
    { min: 9, max: 20 },
    edu2Plus("DEX"),
    [
      requirement("climb", exact(standard("climb"))),
      requirement("dodge", exact(standard("dodge"))),
      requirement("jump", exact(standard("jump"))),
      requirement("throw", exact(standard("throw"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("swim", exact(standard("swim"))),
      requirement("personal-or-era-specialties", anySkill(), 2, 2, true, personalOrEraGuidance),
    ],
    "media-art",
  ),
  defineOccupation(
    "animal-trainer",
    "动物训练师",
    "Animal Trainer",
    [investigatorHandbook(71)],
    { min: 10, max: 40 },
    edu2Plus("APP", "POW"),
    [
      requirement("jump", exact(standard("jump"))),
      requirement("listen", exact(standard("listen"))),
      requirement("natural-world", exact(standard("natural-world"))),
      requirement("animal-handling", exact(standard("animal-handling"))),
      requirement("zoology", exact(predefined("science", "zoology"))),
      requirement("stealth", exact(standard("stealth"))),
      requirement("track", exact(standard("track"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "technical-labor",
  ),
  defineOccupation(
    "athlete",
    "运动员",
    "Athlete",
    [
      keeperRulebook(40, "自由技能遵循本页职业与时代适配总则"),
      investigatorHandbook(72, "个人或时代特长措辞"),
    ],
    { min: 9, max: 70 },
    edu2Plus("DEX", "STR"),
    [
      requirement("climb", exact(standard("climb"))),
      requirement("jump", exact(standard("jump"))),
      requirement("brawl", brawl),
      requirement("ride", exact(standard("ride"))),
      requirement("social", socialSelector),
      requirement("swim", exact(standard("swim"))),
      requirement("throw", exact(standard("throw"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "media-art",
  ),
  defineOccupation(
    "bartender",
    "酒保",
    "Bartender",
    [investigatorHandbook(73)],
    { min: 8, max: 25 },
    edu2Plus("APP"),
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("social", socialSelector, 2, 2),
      requirement("brawl", brawl),
      requirement("listen", exact(standard("listen"))),
      requirement("psychology", exact(standard("psychology"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "business-professional",
  ),
  defineOccupation(
    "boxer-wrestler",
    "拳击手、摔跤手",
    "Boxer / Wrestler",
    [investigatorHandbook(73)],
    { min: 9, max: 60 },
    edu2Plus("STR"),
    [
      requirement("dodge", exact(standard("dodge"))),
      requirement("brawl", brawl),
      requirement("intimidate", exact(standard("intimidate"))),
      requirement("jump", exact(standard("jump"))),
      requirement("psychology", exact(standard("psychology"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("personal-or-era-specialties", anySkill(), 2, 2, true, personalOrEraGuidance),
    ],
    "media-art",
    { aliases: { zh: ["拳击手", "摔跤手"], en: ["Boxer", "Wrestler"] } },
  ),
  defineOccupation(
    "butler-valet-maid",
    "管家、男仆、女仆",
    "Butler / Valet / Maid",
    [investigatorHandbook(74, "信用范围 9–40；具体值取决于雇主家庭的社会地位与信用等级")],
    { min: 9, max: 40 },
    edu4,
    [
      requirement("accounting-or-appraise", oneOf(
        exact(standard("accounting")),
        exact(standard("appraise")),
      )),
      requirement("art-craft", specializationOf("art-craft")),
      requirement("first-aid", exact(standard("first-aid"))),
      requirement("listen", exact(standard("listen"))),
      requirement("psychology", exact(standard("psychology"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("personal-or-era-specialties", anySkill(), 2, 2, true, personalOrEraGuidance),
    ],
    "social-special",
    {
      aliases: {
        zh: ["管家", "男仆", "女仆"],
        en: ["Butler", "Valet", "Maid"],
      },
    },
  ),
  defineOccupation(
    "craftsperson",
    "工匠",
    "Craftsperson",
    [investigatorHandbook(74)],
    { min: 10, max: 40 },
    edu2Plus("DEX"),
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("art-craft-specialties", specializationOf("art-craft"), 2, 2),
      requirement("mechanical-repair", exact(standard("mechanical-repair"))),
      requirement("natural-world", exact(standard("natural-world"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("personal-or-era-specialties", anySkill(), 2, 2, true, personalOrEraGuidance),
    ],
    "technical-labor",
  ),
  defineOccupation(
    "cult-leader",
    "教团首领",
    "Cult Leader",
    [investigatorHandbook(77)],
    { min: 30, max: 60 },
    edu4,
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("social", socialSelector, 2, 2),
      requirement("occult", exact(standard("occult"))),
      requirement("psychology", exact(standard("psychology"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("personal-specialties", anySkill(), 2, 2, true, personalSpecialtyGuidance),
    ],
    "religion-occult",
  ),
  defineOccupation(
    "designer",
    "设计师",
    "Designer",
    [investigatorHandbook(78)],
    { min: 20, max: 60 },
    edu4,
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("photography", exact(predefined("art-craft", "photography"))),
      requirement("art-craft", specializationOf("art-craft")),
      requirement("computer-or-library", oneOf(
        exact(standard("computer-use")),
        exact(standard("library-use")),
      )),
      requirement("mechanical-repair", exact(standard("mechanical-repair"))),
      requirement("psychology", exact(standard("psychology"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("personal-specialty", anySkill(), 1, 1, true, personalSpecialtyGuidance),
    ],
    "media-art",
  ),
  defineOccupation(
    "dilettante",
    "业余艺术爱好者（原作向）",
    "Dilettante",
    [
      keeperRulebook(40, "自由技能遵循本页职业与时代适配总则"),
      investigatorHandbook(78, "个人或时代特长措辞"),
    ],
    { min: 50, max: 99 },
    edu2Plus("APP"),
    [
      requirement("art-craft", specializationOf("art-craft")),
      requirement("firearms", genericFirearms, 1, null),
      requirement("other-language", specializationOf("language-other")),
      requirement("ride", exact(standard("ride"))),
      requirement("social", socialSelector),
      requirement("personal-or-era-specialties", anySkill(), 3, 3, true, personalOrEraGuidance),
    ],
    "social-special",
    { aliases: { zh: ["业余艺术爱好者"] } },
  ),
  defineOccupation(
    "diver",
    "潜水员",
    "Diver",
    [investigatorHandbook(78)],
    { min: 9, max: 30 },
    edu2Plus("DEX"),
    [
      requirement("diving", exact(standard("diving"))),
      requirement("first-aid", exact(standard("first-aid"))),
      requirement("mechanical-repair", exact(standard("mechanical-repair"))),
      requirement("pilot-boat", exact(predefined("pilot", "boat"))),
      requirement("biology", exact(predefined("science", "biology"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("swim", exact(standard("swim"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "outdoor-adventure",
  ),
  defineOccupation(
    "drifter",
    "流浪者",
    "Drifter",
    [
      keeperRulebook(40, "自由技能遵循本页职业与时代适配总则"),
      investigatorHandbook(78, "个人或时代特长措辞"),
    ],
    { min: 0, max: 5 },
    edu2Plus("APP", "DEX", "STR"),
    [
      requirement("climb", exact(standard("climb"))),
      requirement("jump", exact(standard("jump"))),
      requirement("listen", exact(standard("listen"))),
      requirement("navigate", exact(standard("navigate"))),
      requirement("social", socialSelector),
      requirement("stealth", exact(standard("stealth"))),
      requirement("personal-or-era-specialties", anySkill(), 2, 2, true, personalOrEraGuidance),
    ],
    "social-special",
  ),
  defineOccupation(
    "editor",
    "编辑",
    "Editor",
    [investigatorHandbook(79)],
    { min: 10, max: 30 },
    edu4,
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("history", exact(standard("history"))),
      requirement("own-language", specializationOf("language-own")),
      requirement("social", socialSelector, 2, 2),
      requirement("psychology", exact(standard("psychology"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "media-art",
  ),
  defineOccupation(
    "engineer",
    "工程师",
    "Engineer",
    [
      keeperRulebook(40, "固定 Art / Craft (Technical Drawing) 专业"),
      investigatorHandbook(79, "个人或时代特长措辞"),
    ],
    { min: 30, max: 60 },
    edu4,
    [
      requirement(
        "technical-drawing",
        namedCustomSpecialization("art-craft", "技术制图", "Technical Drawing"),
      ),
      requirement("electrical-repair", exact(standard("electrical-repair"))),
      requirement("library-use", exact(standard("library-use"))),
      requirement("mechanical-repair", exact(standard("mechanical-repair"))),
      requirement("operate-heavy-machinery", exact(standard("operate-heavy-machinery"))),
      requirement("engineering", exact(predefined("science", "engineering"))),
      requirement("physics", exact(predefined("science", "physics"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "technical-labor",
  ),
  defineOccupation(
    "entertainer",
    "艺人",
    "Entertainer",
    [
      keeperRulebook(40, "Art / Craft (Performance) 概括措辞"),
      investigatorHandbook(79, "表演、声乐、喜剧等仅为表演类专业示例"),
    ],
    { min: 9, max: 70 },
    edu2Plus("APP"),
    [
      requirement(
        "performing-art-craft",
        specializationOf("art-craft"),
        1,
        1,
        true,
        {
          zh: "适合表演行业的艺术／手艺专业，例如表演、声乐或喜剧",
          en: "an Art / Craft specialization suited to performance, such as acting, singing, or comedy",
        },
      ),
      requirement("disguise", exact(standard("disguise"))),
      requirement("social", socialSelector, 2, 2),
      requirement("listen", exact(standard("listen"))),
      requirement("psychology", exact(standard("psychology"))),
      requirement("personal-or-era-specialties", anySkill(), 2, 2, true, personalOrEraGuidance),
    ],
    "media-art",
  ),
  defineOccupation(
    "farmer",
    "农民",
    "Farmer",
    [
      keeperRulebook(40, "Drive Auto 使用时代适配名称；本书技能章以 Wagon Driving 为旧时代示例"),
      investigatorHandbook(80, "Drive Auto (or Wagon) 使用同一时代适配技能 identity"),
    ],
    { min: 9, max: 30 },
    edu2Plus("DEX", "STR"),
    [
      requirement("farming", namedCustomSpecialization("art-craft", "耕作", "Farming")),
      requirement("drive-auto", exact(standard("drive-auto"))),
      requirement("social", socialSelector),
      requirement("mechanical-repair", exact(standard("mechanical-repair"))),
      requirement("natural-world", exact(standard("natural-world"))),
      requirement("operate-heavy-machinery", exact(standard("operate-heavy-machinery"))),
      requirement("track", exact(standard("track"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "technical-labor",
  ),
];
