import type { OccupationDefinition } from "../../../coc7/types/occupation";

import {
  anySkill,
  defineOccupation,
  edu2Plus,
  edu4,
  exact,
  investigatorHandbook,
  keeperRulebook,
  namedCustomSpecialization,
  oneOf,
  predefined,
  requirement,
  socialSelector,
  specializationOf,
  standard,
} from "./shared";

const acting = exact(predefined("art-craft", "acting"));
const brawl = exact(predefined("fighting", "brawl"));
const genericFighting = specializationOf("fighting");
const genericFirearms = specializationOf("firearms");

export const batch2bOccupationDefinitions: readonly OccupationDefinition[] = [
  defineOccupation(
    "gambler",
    "赌徒",
    "Gambler",
    [investigatorHandbook(81)],
    { min: 8, max: 50 },
    edu2Plus("APP", "DEX"),
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("acting", acting),
      requirement("social", socialSelector, 2, 2),
      requirement("listen", exact(standard("listen"))),
      requirement("psychology", exact(standard("psychology"))),
      requirement("sleight-of-hand", exact(standard("sleight-of-hand"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
    ],
    "criminal-underworld",
  ),
  defineOccupation(
    "gentleman-lady",
    "绅士、淑女",
    "Gentleman / Lady",
    [investigatorHandbook(81)],
    { min: 40, max: 90 },
    edu2Plus("APP"),
    [
      requirement("art-craft", specializationOf("art-craft")),
      requirement("social", socialSelector, 2, 2),
      requirement("rifle-shotgun", exact(predefined("firearms", "rifle-shotgun"))),
      requirement("history", exact(standard("history"))),
      requirement("other-language", specializationOf("language-other")),
      requirement("navigate", exact(standard("navigate"))),
      requirement("ride", exact(standard("ride"))),
    ],
    "social-special",
  ),
  defineOccupation(
    "hospital-orderly",
    "勤杂护工",
    "Hospital Orderly",
    [investigatorHandbook(82)],
    { min: 6, max: 15 },
    edu2Plus("STR"),
    [
      requirement("electrical-repair", exact(standard("electrical-repair"))),
      requirement("social", socialSelector),
      requirement("brawl", brawl),
      requirement("first-aid", exact(standard("first-aid"))),
      requirement("listen", exact(standard("listen"))),
      requirement("mechanical-repair", exact(standard("mechanical-repair"))),
      requirement("psychology", exact(standard("psychology"))),
      requirement("stealth", exact(standard("stealth"))),
    ],
    "medical",
  ),
  defineOccupation(
    "mountain-climber",
    "登山家",
    "Mountain Climber",
    [investigatorHandbook(84)],
    { min: 30, max: 60 },
    edu2Plus("DEX", "STR"),
    [
      requirement("climb", exact(standard("climb"))),
      requirement("first-aid", exact(standard("first-aid"))),
      requirement("jump", exact(standard("jump"))),
      requirement("listen", exact(standard("listen"))),
      requirement("navigate", exact(standard("navigate"))),
      requirement("other-language", specializationOf("language-other")),
      requirement(
        "alpine-or-similar-survival",
        specializationOf("survival"),
        1,
        1,
        true,
        {
          zh: "阿尔卑斯或类似山区环境的生存专业",
          en: "Survival (Alpine or similar mountainous environment)",
        },
      ),
      requirement("track", exact(standard("track"))),
    ],
    "outdoor-adventure",
  ),
  defineOccupation(
    "musician",
    "音乐家",
    "Musician",
    [
      keeperRulebook(41, "艺术/手艺（乐器）措辞"),
      investigatorHandbook(84, "艺术（器乐）措辞；中文版本译注确认第二特征为 DEX 或 POW"),
    ],
    { min: 9, max: 30 },
    edu2Plus("DEX", "POW"),
    [
      requirement(
        "musical-instrument",
        specializationOf("art-craft"),
        1,
        1,
        true,
        {
          zh: "乐器或器乐相关的艺术／手艺专业",
          en: "Art / Craft specialization for a musical instrument",
        },
      ),
      requirement("social", socialSelector),
      requirement("listen", exact(standard("listen"))),
      requirement("psychology", exact(standard("psychology"))),
      requirement("other-skills", anySkill(), 4, 4),
    ],
    "media-art",
  ),
  defineOccupation(
    "outdoorsperson",
    "旅行家",
    "Outdoorsman / Outdoorswoman",
    [investigatorHandbook(85)],
    { min: 5, max: 20 },
    edu2Plus("DEX", "STR"),
    [
      requirement("firearms", genericFirearms, 1, null),
      requirement("first-aid", exact(standard("first-aid"))),
      requirement("listen", exact(standard("listen"))),
      requirement("natural-world", exact(standard("natural-world"))),
      requirement("navigate", exact(standard("navigate"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("survival", specializationOf("survival")),
      requirement("track", exact(standard("track"))),
    ],
    "outdoor-adventure",
    { aliases: { en: ["Outdoorsperson"] } },
  ),
  defineOccupation(
    "pharmacist",
    "药剂师",
    "Pharmacist",
    [investigatorHandbook(86)],
    { min: 35, max: 75 },
    edu4,
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("first-aid", exact(standard("first-aid"))),
      requirement("latin", namedCustomSpecialization("language-other", "拉丁文", "Latin")),
      requirement("library-use", exact(standard("library-use"))),
      requirement("social", socialSelector),
      requirement("psychology", exact(standard("psychology"))),
      requirement("pharmacy", exact(predefined("science", "pharmacy"))),
      requirement("chemistry", exact(predefined("science", "chemistry"))),
    ],
    "medical",
  ),
  defineOccupation(
    "psychiatrist",
    "精神病学家",
    "Psychiatrist",
    [investigatorHandbook(88)],
    { min: 30, max: 80 },
    edu4,
    [
      requirement("other-language", specializationOf("language-other")),
      requirement("listen", exact(standard("listen"))),
      requirement("medicine", exact(standard("medicine"))),
      requirement("persuade", exact(standard("persuade"))),
      requirement("psychoanalysis", exact(standard("psychoanalysis"))),
      requirement("psychology", exact(standard("psychology"))),
      requirement("biology", exact(predefined("science", "biology"))),
      requirement("chemistry", exact(predefined("science", "chemistry"))),
    ],
    "medical",
  ),
  defineOccupation(
    "salesperson",
    "推销员",
    "Salesperson",
    [investigatorHandbook(89)],
    { min: 9, max: 40 },
    edu2Plus("APP"),
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("social", socialSelector, 2, 2),
      requirement("drive-auto", exact(standard("drive-auto"))),
      requirement("listen", exact(standard("listen"))),
      requirement("psychology", exact(standard("psychology"))),
      requirement("stealth-or-sleight-of-hand", oneOf(
        exact(standard("stealth")),
        exact(standard("sleight-of-hand")),
      )),
      requirement("other-skill", anySkill()),
    ],
    "business-professional",
  ),
  defineOccupation(
    "shopkeeper",
    "店老板",
    "Shopkeeper",
    [investigatorHandbook(90)],
    { min: 20, max: 40 },
    edu2Plus("APP", "DEX"),
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("social", socialSelector, 2, 2),
      requirement("electrical-repair", exact(standard("electrical-repair"))),
      requirement("listen", exact(standard("listen"))),
      requirement("mechanical-repair", exact(standard("mechanical-repair"))),
      requirement("psychology", exact(standard("psychology"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
    ],
    "business-professional",
  ),
  defineOccupation(
    "spy",
    "间谍",
    "Spy",
    [investigatorHandbook(90)],
    { min: 20, max: 60 },
    edu2Plus("APP", "DEX"),
    [
      requirement("acting-or-disguise", oneOf(
        acting,
        exact(standard("disguise")),
      )),
      requirement("firearms", genericFirearms, 1, null),
      requirement("listen", exact(standard("listen"))),
      requirement("other-language", specializationOf("language-other")),
      requirement("social", socialSelector),
      requirement("psychology", exact(standard("psychology"))),
      requirement("sleight-of-hand", exact(standard("sleight-of-hand"))),
      requirement("stealth", exact(standard("stealth"))),
    ],
    "investigation-security",
  ),
  defineOccupation(
    "stunt-performer",
    "替身演员",
    "Stuntman",
    [investigatorHandbook(90)],
    { min: 10, max: 50 },
    edu2Plus("DEX", "STR"),
    [
      requirement("climb", exact(standard("climb"))),
      requirement("dodge", exact(standard("dodge"))),
      requirement("electrical-or-mechanical-repair", oneOf(
        exact(standard("electrical-repair")),
        exact(standard("mechanical-repair")),
      )),
      requirement("fighting", genericFighting, 1, null),
      requirement("first-aid", exact(standard("first-aid"))),
      requirement("jump", exact(standard("jump"))),
      requirement("swim", exact(standard("swim"))),
      requirement("stunt-specialty", oneOf(
        exact(standard("diving")),
        exact(standard("drive-auto")),
        specializationOf("pilot"),
        exact(standard("ride")),
      )),
    ],
    "media-art",
    { aliases: { en: ["Stunt Performer"] } },
  ),
  defineOccupation(
    "undertaker",
    "殡葬师",
    "Undertaker",
    [investigatorHandbook(91)],
    { min: 20, max: 40 },
    edu4,
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("drive-auto", exact(standard("drive-auto"))),
      requirement("social", socialSelector),
      requirement("history", exact(standard("history"))),
      requirement("occult", exact(standard("occult"))),
      requirement("psychology", exact(standard("psychology"))),
      requirement("biology", exact(predefined("science", "biology"))),
      requirement("chemistry", exact(predefined("science", "chemistry"))),
    ],
    "business-professional",
  ),
  defineOccupation(
    "union-activist",
    "工会活动家",
    "Union Activist",
    [investigatorHandbook(91)],
    { min: 5, max: 50 },
    edu4,
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("social", socialSelector, 2, 2),
      requirement("brawl", brawl),
      requirement("law", exact(standard("law"))),
      requirement("listen", exact(standard("listen"))),
      requirement("operate-heavy-machinery", exact(standard("operate-heavy-machinery"))),
      requirement("psychology", exact(standard("psychology"))),
    ],
    "technical-labor",
  ),
  defineOccupation(
    "zookeeper",
    "饲养员",
    "Zookeeper",
    [investigatorHandbook(93)],
    { min: 9, max: 40 },
    edu4,
    [
      requirement("animal-handling", exact(standard("animal-handling"))),
      requirement("accounting", exact(standard("accounting"))),
      requirement("dodge", exact(standard("dodge"))),
      requirement("first-aid", exact(standard("first-aid"))),
      requirement("natural-world", exact(standard("natural-world"))),
      requirement("medicine", exact(standard("medicine"))),
      requirement("pharmacy", exact(predefined("science", "pharmacy"))),
      requirement("zoology", exact(predefined("science", "zoology"))),
    ],
    "technical-labor",
  ),
];
