import type { OccupationDefinition } from "../../../coc7/types/occupation";

import {
  anySkill,
  defineOccupation,
  edu2Plus,
  edu4,
  exact,
  investigatorHandbook,
  keeperRulebook,
  namedCustomSpecialization,
  oneOf,
  predefined,
  requirement,
  socialSelector,
  specializationOf,
  standard,
} from "./shared";

const brawl = exact(predefined("fighting", "brawl"));
const genericFirearms = specializationOf("firearms");

export const batch2aOccupationDefinitions: readonly OccupationDefinition[] = [
  defineOccupation(
    "agency-detective",
    "事务所侦探",
    "Agency Detective",
    [investigatorHandbook(71)],
    { min: 20, max: 45 },
    edu2Plus("DEX", "STR"),
    [
      requirement("social", socialSelector),
      requirement("brawl", brawl),
      requirement("firearms", genericFirearms, 1, null),
      requirement("law", exact(standard("law"))),
      requirement("library-use", exact(standard("library-use"))),
      requirement("psychology", exact(standard("psychology"))),
      requirement("stealth", exact(standard("stealth"))),
      requirement("track", exact(standard("track"))),
    ],
    "investigation-security",
  ),
  defineOccupation(
    "alienist",
    "精神病医生（古典）",
    "Alienist",
    [investigatorHandbook(71)],
    { min: 10, max: 60 },
    edu4,
    [
      requirement("law", exact(standard("law"))),
      requirement("listen", exact(standard("listen"))),
      requirement("medicine", exact(standard("medicine"))),
      requirement("other-language", specializationOf("language-other")),
      requirement("psychoanalysis", exact(standard("psychoanalysis"))),
      requirement("psychology", exact(standard("psychology"))),
      requirement("biology", exact(predefined("science", "biology"))),
      requirement("chemistry", exact(predefined("science", "chemistry"))),
    ],
    "medical",
    {
      aliases: { zh: ["精神病医生"] },
      era: { type: "specific", eraIds: ["classic-1920s"] },
    },
  ),
  defineOccupation(
    "antique-dealer",
    "古董商",
    "Antique Dealer",
    [investigatorHandbook(71)],
    { min: 30, max: 50 },
    edu4,
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("appraise", exact(standard("appraise"))),
      requirement("drive-auto", exact(standard("drive-auto"))),
      requirement("social", socialSelector, 2, 2),
      requirement("history", exact(standard("history"))),
      requirement("library-use", exact(standard("library-use"))),
      requirement("navigate", exact(standard("navigate"))),
    ],
    "business-professional",
  ),
  defineOccupation(
    "archaeologist",
    "考古学家（原作向）",
    "Archaeologist",
    [investigatorHandbook(72)],
    { min: 10, max: 40 },
    edu4,
    [
      requirement("appraise", exact(standard("appraise"))),
      requirement("archaeology", exact(standard("archaeology"))),
      requirement("history", exact(standard("history"))),
      requirement("other-language", specializationOf("language-other")),
      requirement("library-use", exact(standard("library-use"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("mechanical-repair", exact(standard("mechanical-repair"))),
      requirement("navigate-or-science", oneOf(
        exact(standard("navigate")),
        specializationOf("science"),
      )),
    ],
    "academic",
    { aliases: { zh: ["考古学家"] } },
  ),
  defineOccupation(
    "architect",
    "建筑师",
    "Architect",
    [investigatorHandbook(72)],
    { min: 30, max: 70 },
    edu4,
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement(
        "technical-drawing",
        namedCustomSpecialization("art-craft", "技术制图", "Technical Drawing"),
      ),
      requirement("law", exact(standard("law"))),
      requirement("own-language", specializationOf("language-own")),
      requirement("computer-or-library", oneOf(
        exact(standard("computer-use")),
        exact(standard("library-use")),
      )),
      requirement("persuade", exact(standard("persuade"))),
      requirement("psychology", exact(standard("psychology"))),
      requirement("mathematics", exact(predefined("science", "mathematics"))),
    ],
    "business-professional",
  ),
  defineOccupation(
    "asylum-attendant",
    "精神病院看护",
    "Asylum Attendant",
    [investigatorHandbook(72)],
    { min: 8, max: 20 },
    edu2Plus("DEX", "STR"),
    [
      requirement("dodge", exact(standard("dodge"))),
      requirement("brawl", brawl),
      requirement("first-aid", exact(standard("first-aid"))),
      requirement("social", socialSelector, 2, 2),
      requirement("listen", exact(standard("listen"))),
      requirement("psychology", exact(standard("psychology"))),
      requirement("stealth", exact(standard("stealth"))),
    ],
    "medical",
  ),
  defineOccupation(
    "big-game-hunter",
    "猎人",
    "Big Game Hunter",
    [investigatorHandbook(73)],
    { min: 20, max: 50 },
    edu2Plus("DEX", "STR"),
    [
      requirement("firearms", genericFirearms, 1, null),
      requirement("listen-or-spot-hidden", oneOf(
        exact(standard("listen")),
        exact(standard("spot-hidden")),
      )),
      requirement("natural-world", exact(standard("natural-world"))),
      requirement("navigate", exact(standard("navigate"))),
      requirement("language-or-survival", oneOf(
        specializationOf("language-other"),
        specializationOf("survival"),
      )),
      requirement("biology-or-botany", oneOf(
        exact(predefined("science", "biology")),
        exact(predefined("science", "botany")),
      )),
      requirement("stealth", exact(standard("stealth"))),
      requirement("track", exact(standard("track"))),
    ],
    "outdoor-adventure",
  ),
  defineOccupation(
    "book-dealer",
    "书商",
    "Book Dealer",
    [investigatorHandbook(73, "职业标题始于印刷页 72；职业技能列表见印刷页 73")],
    { min: 20, max: 40 },
    edu4,
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("appraise", exact(standard("appraise"))),
      requirement("drive-auto", exact(standard("drive-auto"))),
      requirement("history", exact(standard("history"))),
      requirement("library-use", exact(standard("library-use"))),
      requirement("own-language", specializationOf("language-own")),
      requirement("other-language", specializationOf("language-other")),
      requirement("social", socialSelector),
    ],
    "business-professional",
  ),
  defineOccupation(
    "explorer",
    "探险家（古典）",
    "Explorer",
    [investigatorHandbook(80)],
    { min: 55, max: 80 },
    edu2Plus("APP", "DEX", "STR"),
    [
      requirement("climb-or-swim", oneOf(
        exact(standard("climb")),
        exact(standard("swim")),
      )),
      requirement("firearms", genericFirearms, 1, null),
      requirement("history", exact(standard("history"))),
      requirement("jump", exact(standard("jump"))),
      requirement("natural-world", exact(standard("natural-world"))),
      requirement("navigate", exact(standard("navigate"))),
      requirement("other-language", specializationOf("language-other")),
      requirement("survival", specializationOf("survival")),
    ],
    "outdoor-adventure",
    {
      aliases: { zh: ["探险家"] },
      era: { type: "specific", eraIds: ["classic-1920s"] },
    },
  ),
  defineOccupation(
    "firefighter",
    "消防员",
    "Firefighter",
    [investigatorHandbook(80)],
    { min: 9, max: 30 },
    edu2Plus("DEX", "STR"),
    [
      requirement("climb", exact(standard("climb"))),
      requirement("dodge", exact(standard("dodge"))),
      requirement("drive-auto", exact(standard("drive-auto"))),
      requirement("first-aid", exact(standard("first-aid"))),
      requirement("jump", exact(standard("jump"))),
      requirement("mechanical-repair", exact(standard("mechanical-repair"))),
      requirement("operate-heavy-machinery", exact(standard("operate-heavy-machinery"))),
      requirement("throw", exact(standard("throw"))),
    ],
    "investigation-security",
  ),
  defineOccupation(
    "forensic-surgeon",
    "法医",
    "Forensic Surgeon",
    [investigatorHandbook(80)],
    { min: 40, max: 60 },
    edu4,
    [
      requirement("latin", namedCustomSpecialization("language-other", "拉丁文", "Latin")),
      requirement("library-use", exact(standard("library-use"))),
      requirement("medicine", exact(standard("medicine"))),
      requirement("persuade", exact(standard("persuade"))),
      requirement("biology", exact(predefined("science", "biology"))),
      requirement("forensics", exact(predefined("science", "forensics"))),
      requirement("pharmacy", exact(predefined("science", "pharmacy"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
    ],
    "medical",
  ),
  defineOccupation(
    "lawyer",
    "律师",
    "Lawyer",
    [keeperRulebook(41), investigatorHandbook(83)],
    { min: 30, max: 80 },
    edu4,
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("law", exact(standard("law"))),
      requirement("library-use", exact(standard("library-use"))),
      requirement("social", socialSelector, 2, 2),
      requirement("psychology", exact(standard("psychology"))),
      requirement("other-skills", anySkill(), 2, 2),
    ],
    "military-government-law",
  ),
  defineOccupation(
    "nurse",
    "护士",
    "Nurse",
    [investigatorHandbook(84)],
    { min: 9, max: 30 },
    edu4,
    [
      requirement("first-aid", exact(standard("first-aid"))),
      requirement("listen", exact(standard("listen"))),
      requirement("medicine", exact(standard("medicine"))),
      requirement("social", socialSelector),
      requirement("psychology", exact(standard("psychology"))),
      requirement("biology", exact(predefined("science", "biology"))),
      requirement("chemistry", exact(predefined("science", "chemistry"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
    ],
    "medical",
  ),
  defineOccupation(
    "police-officer",
    "警察",
    "Police Officer",
    [keeperRulebook(41), investigatorHandbook(87)],
    { min: 9, max: 30 },
    edu2Plus("DEX", "STR"),
    [
      requirement("brawl", brawl),
      requirement("firearms", genericFirearms, 1, null),
      requirement("first-aid", exact(standard("first-aid"))),
      requirement("social", socialSelector),
      requirement("law", exact(standard("law"))),
      requirement("psychology", exact(standard("psychology"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("drive-auto-or-ride", oneOf(
        exact(standard("drive-auto")),
        exact(standard("ride")),
      )),
    ],
    "investigation-security",
    {
      variantOf: "police",
      aliases: {
        zh: ["警官", "警方(原作向)-巡警"],
        en: ["Uniformed Police Officer"],
      },
    },
  ),
];
