import type { OccupationDefinition } from "../../../coc7/types/occupation";

import {
  anySkill,
  defineOccupation,
  edu2Plus,
  edu4,
  exact,
  investigatorHandbook,
  keeperRulebook,
  oneOf,
  personalOrEraGuidance,
  predefined,
  requirement,
  socialSelector,
  specializationOf,
  standard,
} from "./shared";

const genericFighting = specializationOf("fighting");
const genericFirearms = specializationOf("firearms");
const aircraft = exact(predefined("pilot", "aircraft"));
const boat = exact(predefined("pilot", "boat"));
const photography = exact(predefined("art-craft", "photography"));
const chemistry = exact(predefined("science", "chemistry"));

export const batch3dOccupationDefinitions: readonly OccupationDefinition[] = [
  defineOccupation(
    "laborer-unskilled",
    "非熟练工人",
    "Laborer, Unskilled",
    [investigatorHandbook(82)],
    { min: 9, max: 30 },
    edu2Plus("DEX", "STR"),
    [
      requirement("drive-auto", exact(standard("drive-auto"))),
      requirement("electrical-repair", exact(standard("electrical-repair"))),
      requirement("fighting", genericFighting, 1, null),
      requirement("first-aid", exact(standard("first-aid"))),
      requirement("mechanical-repair", exact(standard("mechanical-repair"))),
      requirement("operate-heavy-machinery", exact(standard("operate-heavy-machinery"))),
      requirement("throw", exact(standard("throw"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "technical-labor",
    { variantOf: "laborer" },
  ),
  defineOccupation(
    "laborer-lumberjack",
    "伐木工",
    "Lumberjack",
    [investigatorHandbook(82)],
    { min: 9, max: 30 },
    edu2Plus("DEX", "STR"),
    [
      requirement("climb", exact(standard("climb"))),
      requirement("dodge", exact(standard("dodge"))),
      requirement("chainsaw", exact(predefined("fighting", "chainsaw"))),
      requirement("first-aid", exact(standard("first-aid"))),
      requirement("jump", exact(standard("jump"))),
      requirement("mechanical-repair", exact(standard("mechanical-repair"))),
      requirement("natural-world-or-biology-or-botany", oneOf(
        exact(standard("natural-world")),
        exact(predefined("science", "biology")),
        exact(predefined("science", "botany")),
      )),
      requirement("throw", exact(standard("throw"))),
    ],
    "technical-labor",
    { variantOf: "laborer" },
  ),
  defineOccupation(
    "laborer-miner",
    "矿工",
    "Miner",
    [investigatorHandbook(83)],
    { min: 9, max: 30 },
    edu2Plus("DEX", "STR"),
    [
      requirement("climb", exact(standard("climb"))),
      requirement("geology", exact(predefined("science", "geology"))),
      requirement("jump", exact(standard("jump"))),
      requirement("mechanical-repair", exact(standard("mechanical-repair"))),
      requirement("operate-heavy-machinery", exact(standard("operate-heavy-machinery"))),
      requirement("stealth", exact(standard("stealth"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "technical-labor",
    { variantOf: "laborer" },
  ),
  defineOccupation(
    "photographer-general",
    "摄影师",
    "Photographer",
    [investigatorHandbook(86)],
    { min: 9, max: 30 },
    edu4,
    [
      requirement("photography", photography),
      requirement("social", socialSelector),
      requirement("psychology", exact(standard("psychology"))),
      requirement("chemistry", chemistry),
      requirement("stealth", exact(standard("stealth"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("personal-or-era-specialties", anySkill(), 2, 2, true, personalOrEraGuidance),
    ],
    "media-art",
    { variantOf: "photographer" },
  ),
  defineOccupation(
    "photographer-photojournalist",
    "摄影记者",
    "Photojournalist",
    [investigatorHandbook(86)],
    { min: 10, max: 30 },
    edu4,
    [
      requirement("photography", photography),
      requirement("climb", exact(standard("climb"))),
      requirement("social", socialSelector),
      requirement("other-language", specializationOf("language-other")),
      requirement("psychology", exact(standard("psychology"))),
      requirement("chemistry", chemistry),
      requirement("personal-or-era-specialties", anySkill(), 2, 2, true, personalOrEraGuidance),
    ],
    "media-art",
    { variantOf: "photographer" },
  ),
  defineOccupation(
    "pilot-general",
    "飞行员",
    "Pilot",
    [
      keeperRulebook(41, "任意两项其他技能结合印刷页 40 的职业与时代适配总则"),
      investigatorHandbook(87, "个人或时代特长措辞；规范化为 broad selector 与 Keeper review"),
    ],
    { min: 20, max: 70 },
    edu2Plus("DEX"),
    [
      requirement("electrical-repair", exact(standard("electrical-repair"))),
      requirement("mechanical-repair", exact(standard("mechanical-repair"))),
      requirement("navigate", exact(standard("navigate"))),
      requirement("operate-heavy-machinery", exact(standard("operate-heavy-machinery"))),
      requirement("aircraft", aircraft),
      requirement("astronomy", exact(predefined("science", "astronomy"))),
      requirement("personal-or-era-specialties", anySkill(), 2, 2, true, personalOrEraGuidance),
    ],
    "technical-labor",
    { variantOf: "pilot" },
  ),
  defineOccupation(
    "pilot-stunt",
    "特技飞行员",
    "Aviator / Stunt Pilot",
    [investigatorHandbook(87)],
    { min: 30, max: 60 },
    edu4,
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("electrical-repair", exact(standard("electrical-repair"))),
      requirement("listen", exact(standard("listen"))),
      requirement("mechanical-repair", exact(standard("mechanical-repair"))),
      requirement("navigate", exact(standard("navigate"))),
      requirement("aircraft", aircraft),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "technical-labor",
    {
      aliases: { zh: ["特技飞行员（古典）"], en: ["Stunt Pilot", "Aviator"] },
      variantOf: "pilot",
      era: { type: "specific", eraIds: ["classic-1920s"] },
    },
  ),
  defineOccupation(
    "sailor-naval",
    "军舰海员",
    "Sailor, Naval",
    [investigatorHandbook(89)],
    { min: 9, max: 30 },
    edu2Plus("DEX", "STR"),
    [
      requirement("electrical-or-mechanical-repair", oneOf(
        exact(standard("electrical-repair")),
        exact(standard("mechanical-repair")),
      )),
      requirement("fighting", genericFighting, 1, null),
      requirement("firearms", genericFirearms, 1, null),
      requirement("first-aid", exact(standard("first-aid"))),
      requirement("navigate", exact(standard("navigate"))),
      requirement("boat", boat),
      requirement("survival-sea", exact(predefined("survival", "sea"))),
      requirement("swim", exact(standard("swim"))),
    ],
    "technical-labor",
    { variantOf: "sailor" },
  ),
  defineOccupation(
    "sailor-commercial",
    "民用船海员",
    "Sailor, Commercial",
    [investigatorHandbook(89)],
    { min: 20, max: 40 },
    edu2Plus("DEX", "STR"),
    [
      requirement("first-aid", exact(standard("first-aid"))),
      requirement("mechanical-repair", exact(standard("mechanical-repair"))),
      requirement("natural-world", exact(standard("natural-world"))),
      requirement("navigate", exact(standard("navigate"))),
      requirement("social", socialSelector),
      requirement("boat", boat),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("swim", exact(standard("swim"))),
    ],
    "technical-labor",
    { variantOf: "sailor" },
  ),
  defineOccupation(
    "white-collar-worker-clerk-executive",
    "职员/主管",
    "Clerk / Executive",
    [investigatorHandbook(
      91,
      "职业标题与公式见印刷页 91；技能列表见印刷页 92",
    )],
    { min: 9, max: 20 },
    edu4,
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("language", oneOf(
        specializationOf("language-own"),
        specializationOf("language-other"),
      )),
      requirement("law", exact(standard("law"))),
      requirement("library-or-computer", oneOf(
        exact(standard("library-use")),
        exact(standard("computer-use")),
      )),
      requirement("listen", exact(standard("listen"))),
      requirement("social", socialSelector),
      requirement("personal-or-era", anySkill(), 2, 2, true, personalOrEraGuidance),
    ],
    "business-professional",
    { variantOf: "white-collar-worker" },
  ),
  defineOccupation(
    "white-collar-worker-middle-senior-manager",
    "中层、高层管理人员",
    "Middle / Senior Manager",
    [investigatorHandbook(93)],
    { min: 20, max: 80 },
    edu4,
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("other-language", specializationOf("language-other")),
      requirement("law", exact(standard("law"))),
      requirement("social", socialSelector, 2, 2),
      requirement("psychology", exact(standard("psychology"))),
      requirement("personal-or-era-specialties", anySkill(), 2, 2, true, personalOrEraGuidance),
    ],
    "business-professional",
    {
      aliases: {
        zh: ["中层管理人员", "高层管理人员"],
        en: ["Middle Manager", "Senior Manager"],
      },
      variantOf: "white-collar-worker",
    },
  ),
];
