import type { OccupationDefinition } from "../../../coc7/types/occupation";

import {
  anySkill,
  defineOccupation,
  edu2Plus,
  edu4,
  exact,
  investigatorHandbook,
  keeperRulebook,
  namedCustomSpecialization,
  oneOf,
  personalOrEraGuidance,
  predefined,
  requirement,
  socialSelector,
  specializationOf,
  standard,
} from "./shared";

const brawl = exact(predefined("fighting", "brawl"));
const genericFirearms = specializationOf("firearms");
const photography = exact(predefined("art-craft", "photography"));

const librarianSpecialtyGuidance = {
  zh: "个人专长或专业阅读主题",
  en: "personal specialty or professional reading topic",
};

const technicalTradeGuidance = {
  zh: "与技师职业相关的工艺专业，例如木工、焊接或管道工",
  en: "an Art / Craft specialization related to the trade, such as carpentry, welding, or plumbing",
};

const personalEraOrTechnicalGuidance = {
  zh: "其他个人、时代或技术特长",
  en: "other personal, era, or technical specialty",
};

const academicPersonalOrEraGuidance = {
  zh: "其他学术、个人或时代特长",
  en: "other academic, personal, or era specialty",
};

const academicFieldGuidance = {
  zh: "其他学术领域",
  en: "other academic field",
};

export const batch3bOccupationDefinitions: readonly OccupationDefinition[] = [
  defineOccupation(
    "federal-agent",
    "联邦探员",
    "Federal Agent",
    [investigatorHandbook(80)],
    { min: 20, max: 40 },
    edu4,
    [
      requirement("drive-auto", exact(standard("drive-auto"))),
      requirement("brawl", brawl),
      requirement("firearms", genericFirearms, 1, null),
      requirement("law", exact(standard("law"))),
      requirement("persuade", exact(standard("persuade"))),
      requirement("stealth", exact(standard("stealth"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "investigation-security",
  ),
  defineOccupation(
    "foreign-correspondent",
    "驻外记者",
    "Foreign Correspondent",
    [investigatorHandbook(80)],
    { min: 10, max: 40 },
    edu4,
    [
      requirement("history", exact(standard("history"))),
      requirement("other-language", specializationOf("language-other")),
      requirement("own-language", specializationOf("language-own")),
      requirement("listen", exact(standard("listen"))),
      requirement("social", socialSelector, 2, 2),
      requirement("psychology", exact(standard("psychology"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "media-art",
  ),
  defineOccupation(
    "hobo",
    "游民",
    "Hobo",
    [investigatorHandbook(81)],
    { min: 0, max: 5 },
    edu2Plus("APP", "DEX"),
    [
      requirement("art-craft", specializationOf("art-craft")),
      requirement("climb", exact(standard("climb"))),
      requirement("jump", exact(standard("jump"))),
      requirement("listen", exact(standard("listen"))),
      requirement("locksmith-or-sleight-of-hand", oneOf(
        exact(standard("locksmith")),
        exact(standard("sleight-of-hand")),
      )),
      requirement("navigate", exact(standard("navigate"))),
      requirement("stealth", exact(standard("stealth"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "social-special",
  ),
  defineOccupation(
    "librarian",
    "图书馆管理员（原作向）",
    "Librarian",
    [
      keeperRulebook(41, "四项选择限定为个人专长或专业阅读主题"),
      investigatorHandbook(83, "四项选择限定为个人特长或专业书籍主题"),
    ],
    { min: 9, max: 35 },
    edu4,
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("library-use", exact(standard("library-use"))),
      requirement("other-language", specializationOf("language-other")),
      requirement("own-language", specializationOf("language-own")),
      requirement("personal-or-professional-reading-specialties", anySkill(), 4, 4, true, librarianSpecialtyGuidance),
    ],
    "academic",
    { aliases: { zh: ["图书馆管理员"] } },
  ),
  defineOccupation(
    "mechanic",
    "技师",
    "Mechanic (and Skilled Trades)",
    [investigatorHandbook(83)],
    { min: 9, max: 40 },
    edu4,
    [
      requirement("trade-art-craft", specializationOf("art-craft"), 1, 1, true, technicalTradeGuidance),
      requirement("climb", exact(standard("climb"))),
      requirement("drive-auto", exact(standard("drive-auto"))),
      requirement("electrical-repair", exact(standard("electrical-repair"))),
      requirement("mechanical-repair", exact(standard("mechanical-repair"))),
      requirement("operate-heavy-machinery", exact(standard("operate-heavy-machinery"))),
      requirement("personal-era-or-technical-specialties", anySkill(), 2, 2, true, personalEraOrTechnicalGuidance),
    ],
    "technical-labor",
    { aliases: { en: ["Mechanic"] } },
  ),
  defineOccupation(
    "occultist",
    "神秘学家",
    "Occultist",
    [investigatorHandbook(84, "最后一项经 Keeper 允许可选择 Cthulhu Mythos；建议起始不高于 10%")],
    { min: 9, max: 65 },
    edu4,
    [
      requirement("anthropology", exact(standard("anthropology"))),
      requirement("history", exact(standard("history"))),
      requirement("library-use", exact(standard("library-use"))),
      requirement("social", socialSelector),
      requirement("occult", exact(standard("occult"))),
      requirement("other-language", specializationOf("language-other")),
      requirement("astronomy", exact(predefined("science", "astronomy"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "religion-occult",
  ),
  defineOccupation(
    "parapsychologist",
    "超心理学家",
    "Parapsychologist",
    [
      keeperRulebook(41, "任意其他技能结合印刷页 40 的职业与时代适配总则"),
      investigatorHandbook(85, "个人或时代特长措辞"),
    ],
    { min: 9, max: 30 },
    edu4,
    [
      requirement("anthropology", exact(standard("anthropology"))),
      requirement("photography", photography),
      requirement("history", exact(standard("history"))),
      requirement("library-use", exact(standard("library-use"))),
      requirement("occult", exact(standard("occult"))),
      requirement("other-language", specializationOf("language-other")),
      requirement("psychology", exact(standard("psychology"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "religion-occult",
  ),
  defineOccupation(
    "private-investigator",
    "私家侦探",
    "Private Investigator",
    [
      keeperRulebook(41, "任意其他技能结合印刷页 40 的职业与时代适配总则"),
      investigatorHandbook(87, "个人或时代特长措辞；计算机、锁匠、格斗与射击仅为示例"),
    ],
    { min: 9, max: 30 },
    edu2Plus("DEX", "STR"),
    [
      requirement("photography", photography),
      requirement("disguise", exact(standard("disguise"))),
      requirement("law", exact(standard("law"))),
      requirement("library-use", exact(standard("library-use"))),
      requirement("social", socialSelector),
      requirement("psychology", exact(standard("psychology"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "investigation-security",
  ),
  defineOccupation(
    "prospector",
    "淘金客",
    "Prospector",
    [investigatorHandbook(88)],
    { min: 0, max: 10 },
    edu2Plus("DEX", "STR"),
    [
      requirement("climb", exact(standard("climb"))),
      requirement("first-aid", exact(standard("first-aid"))),
      requirement("history", exact(standard("history"))),
      requirement("mechanical-repair", exact(standard("mechanical-repair"))),
      requirement("navigate", exact(standard("navigate"))),
      requirement("geology", exact(predefined("science", "geology"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "outdoor-adventure",
  ),
  defineOccupation(
    "psychologist-psychoanalyst",
    "心理学家、心理分析学家",
    "Psychologist / Psychoanalyst",
    [investigatorHandbook(88)],
    { min: 10, max: 40 },
    edu4,
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("library-use", exact(standard("library-use"))),
      requirement("listen", exact(standard("listen"))),
      requirement("persuade", exact(standard("persuade"))),
      requirement("psychoanalysis", exact(standard("psychoanalysis"))),
      requirement("psychology", exact(standard("psychology"))),
      requirement("academic-personal-or-era-specialties", anySkill(), 2, 2, true, academicPersonalOrEraGuidance),
    ],
    "medical",
    {
      aliases: {
        zh: ["心理学家", "心理分析学家", "精神分析学家"],
        en: ["Psychologist", "Psychoanalyst"],
      },
    },
  ),
  defineOccupation(
    "researcher",
    "研究员",
    "Researcher",
    [investigatorHandbook(89)],
    { min: 9, max: 30 },
    edu4,
    [
      requirement("history", exact(standard("history"))),
      requirement("library-use", exact(standard("library-use"))),
      requirement("social", socialSelector),
      requirement("other-language", specializationOf("language-other")),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("academic-fields", anySkill(), 3, 3, true, academicFieldGuidance),
    ],
    "academic",
  ),
  defineOccupation(
    "scientist",
    "科学家",
    "Scientist",
    [investigatorHandbook(89)],
    { min: 9, max: 50 },
    edu4,
    [
      requirement("science-specialties", specializationOf("science"), 3, 3),
      requirement("computer-or-library", oneOf(
        exact(standard("computer-use")),
        exact(standard("library-use")),
      )),
      requirement("other-language", specializationOf("language-other")),
      requirement("own-language", specializationOf("language-own")),
      requirement("social", socialSelector),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
    ],
    "academic",
  ),
  defineOccupation(
    "secretary",
    "秘书",
    "Secretary",
    [investigatorHandbook(90)],
    { min: 9, max: 30 },
    edu2Plus("APP", "DEX"),
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("typing-or-shorthand", oneOf(
        namedCustomSpecialization("art-craft", "打字", "Typing"),
        namedCustomSpecialization("art-craft", "速记", "Shorthand"),
      )),
      requirement("social", socialSelector, 2, 2),
      requirement("own-language", specializationOf("language-own")),
      requirement("computer-or-library", oneOf(
        exact(standard("computer-use")),
        exact(standard("library-use")),
      )),
      requirement("psychology", exact(standard("psychology"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "business-professional",
  ),
  defineOccupation(
    "sex-worker",
    "性工作者",
    "Prostitute",
    [investigatorHandbook(88)],
    { min: 5, max: 50 },
    edu2Plus("APP"),
    [
      requirement("art-craft", specializationOf("art-craft")),
      requirement("social", socialSelector, 2, 2),
      requirement("dodge", exact(standard("dodge"))),
      requirement("psychology", exact(standard("psychology"))),
      requirement("sleight-of-hand", exact(standard("sleight-of-hand"))),
      requirement("stealth", exact(standard("stealth"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "social-special",
    { aliases: { en: ["Sex Worker"] } },
  ),
  defineOccupation(
    "waiter",
    "服务生",
    "Waitress / Waiter",
    [investigatorHandbook(91, "职业标题与公式见印刷页 91；技能列表见印刷页 92")],
    { min: 9, max: 20 },
    edu2Plus("APP", "DEX"),
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("art-craft", specializationOf("art-craft")),
      requirement("dodge", exact(standard("dodge"))),
      requirement("listen", exact(standard("listen"))),
      requirement("social", socialSelector, 2, 2),
      requirement("psychology", exact(standard("psychology"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "business-professional",
    {
      aliases: {
        zh: ["服务员"],
        en: ["Waitress", "Waiter"],
      },
    },
  ),
  defineOccupation(
    "zealot",
    "狂热者",
    "Zealot",
    [
      keeperRulebook(41, "任意其他技能结合印刷页 40 的职业与时代适配总则"),
      investigatorHandbook(93, "个人或时代特长措辞"),
    ],
    { min: 0, max: 30 },
    edu2Plus("APP", "POW"),
    [
      requirement("history", exact(standard("history"))),
      requirement("social", socialSelector, 2, 2),
      requirement("psychology", exact(standard("psychology"))),
      requirement("stealth", exact(standard("stealth"))),
      requirement("personal-or-era-specialties", anySkill(), 3, 3, true, personalOrEraGuidance),
    ],
    "religion-occult",
  ),
];
