import type { OccupationDefinition } from "../../../coc7/types/occupation";

import {
  anySkill,
  defineOccupation,
  edu2Plus,
  edu4,
  exact,
  investigatorHandbook,
  keeperRulebook,
  personalOrEraGuidance,
  predefined,
  requirement,
  socialSelector,
  specializationOf,
  standard,
} from "./shared";

const genericFighting = specializationOf("fighting");
const genericFirearms = specializationOf("firearms");

export const batch3cOccupationDefinitions: readonly OccupationDefinition[] = [
  defineOccupation(
    "actor-stage",
    "戏剧演员",
    "Stage Actor",
    [investigatorHandbook(71)],
    { min: 9, max: 40 },
    edu2Plus("APP"),
    [
      requirement("acting", exact(predefined("art-craft", "acting"))),
      requirement("disguise", exact(standard("disguise"))),
      requirement("fighting", genericFighting, 1, null),
      requirement("history", exact(standard("history"))),
      requirement("social", socialSelector, 2, 2),
      requirement("psychology", exact(standard("psychology"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "media-art",
    { variantOf: "actor" },
  ),
  defineOccupation(
    "actor-film-star",
    "电影演员",
    "Film Star",
    [investigatorHandbook(71)],
    { min: 20, max: 90 },
    edu2Plus("APP"),
    [
      requirement("acting", exact(predefined("art-craft", "acting"))),
      requirement("disguise", exact(standard("disguise"))),
      requirement("drive-auto", exact(standard("drive-auto"))),
      requirement("social", socialSelector, 2, 2),
      requirement("psychology", exact(standard("psychology"))),
      requirement("personal-or-era-specialties", anySkill(), 2, 2, true, personalOrEraGuidance),
    ],
    "media-art",
    { variantOf: "actor" },
  ),
  defineOccupation(
    "computer-professional-programmer-technician",
    "计算机程序员、工程师",
    "Computer Programmer / Technician",
    [investigatorHandbook(74)],
    { min: 10, max: 70 },
    edu4,
    [
      requirement("computer-use", exact(standard("computer-use"))),
      requirement("electrical-repair", exact(standard("electrical-repair"))),
      requirement("electronics", exact(standard("electronics"))),
      requirement("library-use", exact(standard("library-use"))),
      requirement("mathematics", exact(predefined("science", "mathematics"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("personal-or-era-specialties", anySkill(), 2, 2, true, personalOrEraGuidance),
    ],
    "technical-labor",
    {
      aliases: {
        zh: ["计算机程序员", "计算机工程师"],
        en: ["Computer Programmer", "Computer Technician"],
      },
      variantOf: "computer-professional",
      era: { type: "specific", eraIds: ["modern"] },
    },
  ),
  defineOccupation(
    "computer-professional-hacker",
    "黑客",
    "Hacker",
    [
      keeperRulebook(41, "现代职业；与调查员手册 Hacker 机械一致"),
      investigatorHandbook(74, "现代职业；与核心规则书 Hacker 机械一致"),
    ],
    { min: 10, max: 70 },
    edu4,
    [
      requirement("computer-use", exact(standard("computer-use"))),
      requirement("electrical-repair", exact(standard("electrical-repair"))),
      requirement("electronics", exact(standard("electronics"))),
      requirement("library-use", exact(standard("library-use"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("social", socialSelector),
      requirement("other-skills", anySkill(), 2, 2),
    ],
    "technical-labor",
    {
      aliases: { zh: ["黑客（现代）"] },
      variantOf: "computer-professional",
      era: { type: "specific", eraIds: ["modern"] },
    },
  ),
  defineOccupation(
    "driver-chauffeur",
    "私人司机",
    "Chauffeur",
    [investigatorHandbook(79)],
    { min: 10, max: 40 },
    edu2Plus("DEX"),
    [
      requirement("drive-auto", exact(standard("drive-auto"))),
      requirement("social", socialSelector, 2, 2),
      requirement("listen", exact(standard("listen"))),
      requirement("mechanical-repair", exact(standard("mechanical-repair"))),
      requirement("navigate", exact(standard("navigate"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "technical-labor",
    { variantOf: "driver" },
  ),
  defineOccupation(
    "driver-general",
    "司机",
    "Driver",
    [investigatorHandbook(79)],
    { min: 9, max: 20 },
    edu2Plus("DEX", "STR"),
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("drive-auto", exact(standard("drive-auto"))),
      requirement("listen", exact(standard("listen"))),
      requirement("social", socialSelector),
      requirement("mechanical-repair", exact(standard("mechanical-repair"))),
      requirement("navigate", exact(standard("navigate"))),
      requirement("psychology", exact(standard("psychology"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "technical-labor",
    { variantOf: "driver" },
  ),
  defineOccupation(
    "driver-taxi",
    "出租车司机",
    "Taxi Driver",
    [investigatorHandbook(79)],
    { min: 9, max: 30 },
    edu2Plus("DEX"),
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("drive-auto", exact(standard("drive-auto"))),
      requirement("electrical-repair", exact(standard("electrical-repair"))),
      requirement("fast-talk", exact(standard("fast-talk"))),
      requirement("mechanical-repair", exact(standard("mechanical-repair"))),
      requirement("navigate", exact(standard("navigate"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "technical-labor",
    { variantOf: "driver" },
  ),
  defineOccupation(
    "gangster-boss",
    "黑帮老大",
    "Gangster Boss",
    [investigatorHandbook(81)],
    { min: 60, max: 95 },
    edu2Plus("APP"),
    [
      requirement("fighting", genericFighting, 1, null),
      requirement("firearms", genericFirearms, 1, null),
      requirement("law", exact(standard("law"))),
      requirement("listen", exact(standard("listen"))),
      requirement("social", socialSelector, 2, 2),
      requirement("psychology", exact(standard("psychology"))),
      requirement("spot-hidden", exact(standard("spot-hidden"))),
    ],
    "criminal-underworld",
    { variantOf: "gangster" },
  ),
  defineOccupation(
    "gangster-underling",
    "马仔",
    "Gangster Underling",
    [investigatorHandbook(81)],
    { min: 9, max: 20 },
    edu2Plus("DEX", "STR"),
    [
      requirement("drive-auto", exact(standard("drive-auto"))),
      requirement("fighting", genericFighting, 1, null),
      requirement("firearms", genericFirearms, 1, null),
      requirement("social", socialSelector, 2, 2),
      requirement("psychology", exact(standard("psychology"))),
      requirement("personal-or-era-specialties", anySkill(), 2, 2, true, personalOrEraGuidance),
    ],
    "criminal-underworld",
    { aliases: { zh: ["黑帮马仔"] }, variantOf: "gangster" },
  ),
  defineOccupation(
    "military-officer-keeper-rulebook",
    "军官（核心规则书）",
    "Military Officer (Keeper Rulebook)",
    [keeperRulebook(41)],
    { min: 20, max: 70 },
    edu2Plus("DEX", "STR"),
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("firearms", genericFirearms, 1, null),
      requirement("navigate", exact(standard("navigate"))),
      requirement("survival", specializationOf("survival")),
      requirement("social", socialSelector, 2, 2),
      requirement("psychology", exact(standard("psychology"))),
      requirement("other-skill", anySkill()),
    ],
    "military-government-law",
    {
      aliases: { zh: ["军官"], en: ["Military Officer"] },
      variantOf: "military-officer",
    },
  ),
  defineOccupation(
    "military-officer-investigator-handbook",
    "军官（调查员手册）",
    "Military Officer (Investigator Handbook)",
    [investigatorHandbook(83)],
    { min: 20, max: 70 },
    edu2Plus("DEX", "STR"),
    [
      requirement("accounting", exact(standard("accounting"))),
      requirement("firearms", genericFirearms, 1, null),
      requirement("navigate", exact(standard("navigate"))),
      requirement("first-aid", exact(standard("first-aid"))),
      requirement("social", socialSelector, 2, 2),
      requirement("psychology", exact(standard("psychology"))),
      requirement("personal-or-era-specialty", anySkill(), 1, 1, true, personalOrEraGuidance),
    ],
    "military-government-law",
    {
      aliases: { zh: ["军官"], en: ["Military Officer"] },
      variantOf: "military-officer",
    },
  ),
];
